"use strict";

const CARD_DATA = {
  "CS 111": { units: {
    "01 · Filesystems, inodes & crash consistency": [
      ["What does a filesystem provide above raw storage?","Named, persistent byte sequences plus directories, metadata, protection, allocation, caching, and recovery rules."],
      ["What information belongs in an inode rather than a directory entry?","The inode stores file type, size, permissions, timestamps, link count, and block pointers. A directory maps a name to an inode number."],
      ["How do a hard link and a symbolic link differ?","A hard link is another name for the same inode and increments its link count. A symbolic link is a distinct file containing a pathname and can dangle."],
      ["When is an unlinked file actually reclaimed?","When both its directory-link count and its open-file-description reference count reach zero."],
      ["How does Unix V6 locate a byte at offset $o$ in a small file?","Compute logical block $\\lfloor o/B\\rfloor$ and in-block offset $o\\bmod B$, then follow the corresponding direct block pointer."],
      ["Why can sparse files have a large logical size but consume few blocks?","Unallocated logical blocks read as zeros; physical blocks are allocated only for regions that are written."],
      ["What is the difference between an inode table entry and an open-file description?","The inode represents the persistent file. The open-file description represents an open instance with status flags and a current offset and is shared by duplicated descriptors."],
      ["Why can two directory entries safely share file metadata?","Both names reference the same inode, so there is one authoritative metadata record and one link count."],
      ["What are the three main crash-consistency choices emphasized in the course?","Careful write ordering, write-ahead logging/journaling, and post-crash repair such as fsck; each trades runtime cost, recovery cost, and guarantees."],
      ["What is the write-ahead logging rule?","Write and durably commit the log record before applying the corresponding home-location updates."],
      ["Why must recovery operations be idempotent?","A crash can occur during recovery. Repeating an already-applied redo step must leave the same correct state."],
      ["Why is delayed write-back useful and dangerous?","It combines writes and returns quickly, but acknowledged data may exist only in volatile memory until flushed."]
    ],
    "02 · File descriptors & system calls": [
      ["What are the three layers behind a Unix file descriptor?","A process descriptor table entry points to a system-wide open-file description, which points to an inode or pipe endpoint."],
      ["What does dup2(oldfd, newfd) do?","It makes newfd refer to the same open-file description as oldfd, first closing newfd if necessary; both descriptors then share offset and status flags."],
      ["After fork, do parent and child share file offsets?","Yes. Their copied descriptor-table entries point to the same open-file descriptions unless one process later opens a separate description."],
      ["What does exec preserve and replace?","It replaces the process address space and program image but preserves the PID and open descriptors except those marked close-on-exec."],
      ["Why should a shell perform redirection before exec?","The child rearranges descriptors with open/dup2/close, then exec starts the target program with standard input/output already connected correctly."],
      ["When does read on a pipe return EOF?","When the pipe buffer is empty and every descriptor referring to the write end has been closed in every process."],
      ["Why can an apparently unused pipe descriptor cause a hang?","Any extra open write end keeps readers from seeing EOF; any extra read end can keep writes from receiving the expected broken-pipe behavior."],
      ["What does a successful read return?","The number of bytes actually read, which may be less than requested; zero means EOF, and -1 reports an error."],
      ["Why must robust code loop around read and write?","System calls may transfer only part of the requested buffer or be interrupted, so callers must track remaining bytes."],
      ["What does O_APPEND guarantee?","Each write chooses the then-current end of file atomically with the write, avoiding a race between seek-to-end and writing."],
      ["What is a descriptor leak across exec?","A descriptor unintentionally survives into a new program, retaining resources or pipe endpoints and potentially exposing data."],
      ["Which flag prevents unintended descriptor inheritance?","The close-on-exec flag, set with O_CLOEXEC at creation or FD_CLOEXEC via fcntl."]
    ],
    "03 · Processes, fork, exec & pipelines": [
      ["What does fork return in parent and child?","The parent receives the child's PID; the child receives 0; failure returns -1 only to the caller because no child was created."],
      ["What state is logically copied by fork?","The address space and descriptor table are copied, usually through copy-on-write pages; open-file descriptions remain shared."],
      ["Why is output buffering important around fork?","Buffered user-space output is copied. If both processes flush it, text written before fork may appear twice."],
      ["What does waitpid prevent?","It collects a terminated child's status and prevents the child from remaining a zombie."],
      ["What is the difference between a zombie and an orphan?","A zombie has terminated but awaits collection. An orphan is still running after its parent exits and is reparented."],
      ["What is the correct high-level order for launching a pipeline stage?","Create required pipes, fork, close/dup descriptors in the child, exec the command, close unused ends in the parent, then wait at the appropriate time."],
      ["Why must a shell create all pipeline processes before waiting?","Waiting after each fork serializes stages and can deadlock when a producer fills its pipe before the consumer exists."],
      ["How does command A | command B connect descriptors?","A's stdout becomes the pipe write end and B's stdin becomes the pipe read end using dup2; all redundant ends are closed."],
      ["What happens when execvp succeeds?","It never returns; the current process image has become the requested program."],
      ["What should a child do if exec fails?","Report the error and terminate with _exit or an equivalent immediate child-safe exit path, rather than falling back into shell logic."],
      ["Why use _exit instead of exit after a post-fork child failure?","exit may flush duplicated stdio buffers and run inherited cleanup handlers; _exit terminates without those user-space effects."],
      ["What isolation does a process boundary provide that a thread boundary does not?","A separate virtual address space and protection domain; threads intentionally share the process's memory and resources."]
    ],
    "04 · Threads, mutexes & condition variables": [
      ["What state do threads in one process share?","Address space, heap, globals, code, and open descriptors. Each thread has its own registers, stack, and scheduling state."],
      ["What is a data race?","Two threads access the same memory concurrently, at least one access is a write, and the accesses are not properly synchronized."],
      ["Why is count++ not atomic?","It expands to read, modify, and write steps that another thread can interleave, causing lost updates."],
      ["What invariant should a mutex protect?","A stated relationship among shared fields, not merely one variable; every path that can break or observe that relationship must follow the locking protocol."],
      ["What does cond.wait(lock) do atomically?","It releases the associated mutex and blocks; before returning it reacquires that mutex."],
      ["Why must condition-variable waits use while, not if?","Under Mesa semantics the predicate may become false before the awakened thread reacquires the lock, and wakeups may also be spurious."],
      ["What information belongs in a condition-variable predicate?","The shared-state condition that makes progress legal, checked while holding the same mutex that protects that state."],
      ["When is signal appropriate versus broadcast?","Signal when one state change enables at most one interchangeable waiter; broadcast when several may proceed or different predicates may now be true."],
      ["What is a monitor?","Shared state bundled with methods, one mutual-exclusion lock, and condition variables used to wait for explicit predicates."],
      ["What four Coffman conditions are necessary for deadlock?","Mutual exclusion, hold-and-wait, no forced preemption of held resources, and circular wait."],
      ["How does a global lock order prevent deadlock?","Every thread acquires locks in the same strict order, making a circular wait impossible."],
      ["How do deadlock and starvation differ?","Deadlock is a permanent dependency impasse among operations; starvation lets the system progress while one participant waits indefinitely."]
    ],
    "05 · Dispatching, preemption & scheduling": [
      ["What must a context switch save and restore?","The architectural register state, stack pointer, program counter, and relevant address-space/scheduling state of the outgoing and incoming thread."],
      ["What is the difference between READY and BLOCKED?","READY means runnable but waiting for a CPU; BLOCKED means unable to run until an event or condition occurs."],
      ["How does a timer interrupt enable preemption?","It transfers control to the kernel after a bounded interval so the scheduler can stop the current thread and dispatch another."],
      ["What is the convoy effect in FIFO scheduling?","Short jobs wait behind a long CPU-bound job, increasing response and average completion times."],
      ["Which policy minimizes average completion time when job lengths are known?","Shortest remaining processing time with preemption; shortest-job-first is the nonpreemptive counterpart."],
      ["How does Round Robin's quantum affect behavior?","A huge quantum approaches FIFO; a tiny quantum improves responsiveness but increases switching and cache overhead."],
      ["Why can shortest-job policies starve work?","A steady arrival of shorter jobs can postpone a long job indefinitely unless aging or another fairness rule intervenes."],
      ["What is a work-conserving scheduler?","It never leaves a processor idle while runnable work is available."],
      ["Why use per-core ready queues?","They reduce global-lock contention and preserve cache affinity; load balancing or work stealing handles imbalance."],
      ["What does priority inversion mean?","A high-priority thread waits for a lock held by a low-priority thread while medium-priority work prevents the holder from running; priority inheritance is one remedy."]
    ],
    "06 · Virtual memory & address translation": [
      ["What four goals motivate virtual memory?","Multitasking, a simple/transparent address model, isolation/protection, and efficient sharing/use of physical memory."],
      ["How does base-and-bound translation work?","Check virtual address against the bound, then add the base; it supports one contiguous region per process."],
      ["What does segmentation add beyond base-and-bound?","Multiple independently based, bounded, and protected variable-sized regions such as code, heap, and stack."],
      ["What fragmentation does paging eliminate?","External fragmentation in physical allocation; it can still create internal fragmentation in the last page."],
      ["For a page size of $2^p$, how is an address split?","The low $p$ bits are the page offset; the remaining high bits are the virtual page number."],
      ["What information is commonly stored in a page-table entry?","Physical frame number plus present, writable, user/supervisor, accessed/reference, dirty, executable, and other architecture-specific bits."],
      ["Why are multilevel page tables useful?","They allocate lower-level tables only for populated virtual-address regions rather than storing one enormous flat table."],
      ["What is the TLB?","A small associative cache of recent virtual-page to physical-frame translations and permission bits."],
      ["What happens on a TLB miss versus a page fault?","A TLB miss triggers a page-table walk for a resident mapping. A page fault requires kernel handling because the mapping is absent or violates protection."],
      ["Why is demand paging possible?","The present bit lets the OS defer loading a page until first access, then resume the faulting instruction after installing it."],
      ["Which replacement policy is optimal but unrealizable online?","MIN: evict the page whose next use is farthest in the future."],
      ["How does the clock algorithm approximate recency?","It scans frames cyclically, clearing set reference bits for a second chance and evicting the first frame found with a clear bit."]
    ],
    "07 · Atomic locks, multicore & storage hardware": [
      ["Why is disabling interrupts insufficient for a multicore lock?","It stops interruption only on the current core; another core can still access the shared lock concurrently."],
      ["What hardware primitive supports multicore locks?","An atomic read-modify-write operation such as exchange, compare-and-swap, or test-and-set, plus the required memory-order semantics."],
      ["Why does test-and-test-and-set reduce contention?","Waiters spin on cached reads and issue an invalidating atomic operation only after observing the lock available."],
      ["Why must blocking a thread be atomic with releasing the wait-queue lock?","Otherwise an unlock/wakeup can occur in between and be lost, leaving the thread asleep forever."],
      ["What is the difference between spinning and blocking?","Spinning consumes CPU while waiting and suits very short waits; blocking yields the CPU but incurs scheduler/context-switch overhead."],
      ["Why must flash erase before rewriting?","Programming can change cells only in one direction; restoring them requires erasing an entire larger erase block."],
      ["What does an FTL do?","It maps logical blocks to physical flash pages while performing garbage collection, wear leveling, and bad-block management."],
      ["What is write amplification?","Physical bytes written divided by logical bytes requested; garbage collection and copying live pages can make it much greater than one."],
      ["What does TRIM communicate?","The filesystem tells the SSD which logical blocks no longer contain live data, reducing unnecessary copying during garbage collection."],
      ["How does DMA differ from programmed I/O?","A DMA controller transfers blocks between device and memory after setup; programmed I/O makes the CPU move each unit through device registers."]
    ],
    "08 · Trust, Meltdown & exam patterns": [
      ["What does it mean to trust a system component?","You accept vulnerability to its behavior because you expect it to satisfy required properties, even without complete control or verification."],
      ["What is over-trust?","The trustor assumes stronger guarantees than the evidence or interface supports; it differs from the component itself behaving dishonestly."],
      ["What isolation assumption did Meltdown violate?","Architecturally forbidden kernel data could transiently influence microarchitectural state, which user code then inferred through a cache side channel."],
      ["Why does squashing speculative instructions not erase a side channel?","Architectural registers roll back, but cache fills and other microarchitectural effects can remain observable."],
      ["How does kernel page-table isolation mitigate Meltdown?","User mode runs with most kernel mappings absent, so speculative user execution cannot address the sensitive kernel pages."],
      ["Exam template for descriptor-table tracing?","Draw process descriptor tables, shared open-file descriptions with offsets/refcounts, and pipe endpoints after every fork, dup2, close, and exec."],
      ["Exam template for condition variables?","Write the shared predicate, identify its protecting mutex, wait in a while loop, update state under the lock, and signal only after the predicate may have changed."],
      ["Exam template for address translation?","Split VPN/offset, walk each indexed level, check permissions/presence, combine physical frame with unchanged offset, then account for TLB/page-fault behavior."]
    ],
    "09 · Worked traces & exam drills": [
      ["An inode table starts at block $s$, blocks hold $k$ inodes, and numbering starts at 1. Which block holds inode $i$?","Block $s+\\lfloor(i-1)/k\\rfloor$; its slot within that block is $(i-1)\\bmod k$."],
      ["A Unix V6 small inode has eight direct 512-byte block addresses. What is its maximum file size?","$8\\cdot512=4096$ bytes. The byte at offset $o$ uses direct entry $\\lfloor o/512\\rfloor$ and offset $o\\bmod512$."],
      ["How do you trace a doubly indirect file-block lookup?","Subtract all direct and single-indirect coverage, divide by pointers per block to choose the first-level indirect block, then use quotient/remainder for the second-level pointer and data block."],
      ["For crash-ordering questions, what must be written before a new directory entry points to an inode?","Initialize the inode and its referenced data first. Otherwise a crash can leave reachable metadata pointing to uninitialized or stale storage."],
      ["What exactly happens when `dup2(oldfd, newfd)` targets an already-open descriptor?","The kernel closes `newfd`, makes it refer to the same open-file description as `oldfd`, and updates reference counts atomically. If the numbers are equal, nothing changes."],
      ["A pipe reader blocks forever after all intended writers finish. What should you inspect first?","Look for any process that still holds a write-end descriptor, including inherited copies after `fork` or `exec`. EOF arrives only when every write end is closed."],
      ["How many processes exist after $n$ unconditional successful `fork()` calls?","$2^n$. For output counting, trace which processes reach each print and remember buffered output present before a fork may be flushed more than once."],
      ["Why must code after a successful `execvp` be treated as an error path?","Success replaces the process image and never returns. Reaching the next statement means `execvp` failed, so report the error and exit the child."],
      ["What is the signal-safe child-reaping pattern?","The handler saves `errno`, repeatedly calls `waitpid(-1,&status,WNOHANG)` until no reapable child remains, restores `errno`, and uses only async-signal-safe operations."],
      ["Why must robust low-level I/O loop?","`read` and `write` may transfer fewer bytes than requested; retry on `EINTR`, advance by the completed count, stop reads on 0, and handle other errors explicitly."],
      ["A monitor controls a one-lane bridge. What belongs in the condition-variable predicate?","Direction, current occupancy, capacity, and any fairness rule. Check the complete safety/admission predicate in a `while` loop while holding the monitor lock."],
      ["Given arrival $a_i$, completion $c_i$, and CPU burst $b_i$, compute turnaround and waiting time.","Turnaround is $c_i-a_i$. Waiting is turnaround minus actual service time: $c_i-a_i-b_i$. Response time uses first-run time instead of completion."],
      ["Base $=4000$, bound $=1200$, virtual address $=900$: physical address or fault?","Valid because $900<1200$; physical address is $4000+900=4900$. The bound is a size/limit, not an ending physical address."],
      ["With 4 KiB pages, split virtual address `0x12345`.","The low 12 bits are offset `0x345`; the remaining high bits form VPN `0x12`. Translation changes the page number but preserves the offset."],
      ["What sequence handles a copy-on-write page fault?","Confirm a write to a present read-only COW mapping, allocate a frame, copy the old page, update the PTE to the new writable frame, adjust reference counts, invalidate the TLB entry, and retry."],
      ["What five drawings solve most CS111 trace problems?","Current processes/threads, per-process descriptor tables, shared kernel objects with references, resource state/predicates, and an ordered event timeline. Update them after every relevant operation."]
    ]
  } },
  "CS 157": { units: {
    "01 · Propositional syntax & semantics": [
      ["What three things must a formal logic specify?","A language (syntax), interpretations that give expressions meaning (semantics), and a proof system for deriving conclusions."],
      ["What is a propositional interpretation?","A total assignment of True or False to every propositional atom. It extends recursively to compound formulas."],
      ["When is $p \\to q$ false?","Only when $p$ is true and $q$ is false."],
      ["Translate: ‘$p$ only if $q$.’","$p \\to q$. The phrase after ‘only if’ is the necessary condition."],
      ["How do you express exclusive-or using $\\land,\\lor,\\neg$?","$(p\\lor q)\\land\\neg(p\\land q)$, equivalently $(p\\land\\neg q)\\lor(\\neg p\\land q)$."],
      ["What is the difference between evaluating a formula and satisfying a set?","Evaluation computes one formula’s truth under an interpretation. An interpretation satisfies a set when it makes every formula in that set true."],
      ["How many rows does a truth table with $n$ distinct atoms have?","$2^n$."],
      ["What is unit propagation?","If a clause contains a unit literal, set it true, delete satisfied clauses, and remove its negation from the remaining clauses."],
      ["How does propositional circuit diagnosis work?","Encode component behavior and observations as formulas; fault assignments that satisfy the theory are candidate diagnoses."],
      ["Why can one English sentence have several logical formalizations?","Scope, attachment, implication direction, and whether ‘or’ is inclusive can be ambiguous. State the intended reading before translating."],
      ["What is operator precedence in the course notation?","Typically $\\neg$ binds tightest, then $\\land$, $\\lor$, $\\to$, and $\\leftrightarrow$; use parentheses whenever ambiguity matters."]
    ],
    "02 · Analysis, entailment & metatheorems": [
      ["Define validity, satisfiability, and contingency.","Valid: true in every interpretation. Satisfiable: true in at least one. Contingent: true in some and false in others."],
      ["What does $\\Gamma \\models \\varphi$ mean?","Every interpretation satisfying all formulas in $\\Gamma$ also satisfies $\\varphi$."],
      ["How do you disprove an entailment?","Give one countermodel that satisfies every premise but falsifies the proposed conclusion."],
      ["How do equivalence and consistency differ?","Equivalent formulas have the same truth value in every interpretation. A set is consistent if its members are jointly satisfiable."],
      ["State the semantic deduction theorem.","$\\Gamma\\cup\\{\\varphi\\}\\models\\psi$ iff $\\Gamma\\models(\\varphi\\to\\psi)$."],
      ["State the refutation test for entailment.","$\\Gamma\\models\\varphi$ iff $\\Gamma\\cup\\{\\neg\\varphi\\}$ is unsatisfiable."],
      ["What is monotonicity of entailment?","Adding premises cannot destroy an existing entailment: if $\\Gamma\\models\\varphi$ and $\\Gamma\\subseteq\\Delta$, then $\\Delta\\models\\varphi$."],
      ["What is vacuous entailment?","If $\\Gamma$ is unsatisfiable, then $\\Gamma\\models\\varphi$ for every $\\varphi$, because there is no model of all premises to serve as a counterexample."],
      ["How is equivalence reduced to validity?","$\\varphi$ and $\\psi$ are equivalent iff $\\varphi\\leftrightarrow\\psi$ is valid."],
      ["What is the quickest exam workflow for a semantic classification?","Identify atoms, search first for a satisfying assignment and a falsifying assignment, then use a full table or algebra only if both are not immediate."],
      ["Object-language versus metalanguage?","The object language contains formulas being studied. The metalanguage is the language in which we discuss truth, models, proofs, and formulas."]
    ],
    "03 · Hilbert, Fitch & resolution proofs": [
      ["What is an axiom schema?","A pattern denoting every formula obtained by uniformly substituting formulas for its metavariables."],
      ["What is modus ponens?","From $\\varphi$ and $\\varphi\\to\\psi$, infer $\\psi$."],
      ["Distinguish $\\Gamma\\models\\varphi$ from $\\Gamma\\vdash\\varphi$.","$\\models$ is semantic entailment over models; $\\vdash$ means a formal derivation exists in the proof system."],
      ["What does soundness say?","If $\\Gamma\\vdash\\varphi$, then $\\Gamma\\models\\varphi$: formal proofs do not derive semantically invalid conclusions."],
      ["What does completeness say?","If $\\Gamma\\models\\varphi$, then $\\Gamma\\vdash\\varphi$: every semantic consequence is formally derivable."],
      ["How does implication introduction work in Fitch?","Assume the antecedent in a subproof, derive the consequent, close the subproof, and infer the implication."],
      ["What is a closed subproof restriction?","Once a subproof closes, its internal lines cannot be cited directly outside it; only the conclusion licensed by the discharge rule escapes."],
      ["How does disjunction elimination work?","From $A\\lor B$, derive the same $C$ under assumption $A$ and under assumption $B$, then conclude $C$."],
      ["How do you convert a formula to CNF?","Eliminate $\\leftrightarrow$ and $\\to$, push negations inward, distribute $\\lor$ over $\\land$, then simplify clauses."],
      ["State the resolution rule.","From $C\\lor p$ and $D\\lor\\neg p$, infer $C\\lor D$."],
      ["How does resolution prove entailment?","Convert the premises and negated conclusion to clauses and resolve until deriving the empty clause."],
      ["Which clauses can usually be discarded during resolution?","Tautological clauses, duplicate literals, and clauses subsumed by a stronger clause; keep enough provenance to reconstruct the proof."]
    ],
    "04 · Relational logic & quantified proofs": [
      ["What does a relational interpretation provide?","A nonempty domain, an object for each constant, and an $n$-ary relation over the domain for each $n$-ary predicate."],
      ["Ground, open, and closed formula?","Ground has no variables. Open has at least one free variable. Closed (a sentence) has no free variables."],
      ["Why do $\\forall x\\exists y\\,R(x,y)$ and $\\exists y\\forall x\\,R(x,y)$ differ?","The first may choose a different witness $y$ for each $x$; the second requires one witness that works for every $x$."],
      ["How do you refute a universally quantified claim?","Exhibit a domain element for which its matrix is false."],
      ["How do you satisfy an existential claim?","Provide one domain element as a witness and verify the matrix for that element."],
      ["Why is grounding finite-domain relational logic useful?","Replace quantifiers by finite conjunctions/disjunctions over named elements, reducing the problem to propositional logic."],
      ["What is prenex form?","A formula with all quantifiers in a prefix followed by a quantifier-free matrix, after safe variable renaming."],
      ["Restriction on universal introduction?","The chosen parameter must be arbitrary: it cannot occur in an undischarged assumption that gives it special properties."],
      ["Restriction on existential elimination?","Use a fresh witness inside a subproof and derive a conclusion that does not depend on that witness."],
      ["Classic invalid witness move?","From $\\exists xP(x)$ and $\\exists xQ(x)$ infer $\\exists x(P(x)\\land Q(x))$. The two existentials may have different witnesses."],
      ["How do logic-grid problems become relational constraints?","Represent categories as domain objects, encode uniqueness and clue relations, add one-to-one constraints, then derive or search for the model."],
      ["Why is full first-order validity harder than propositional validity?","Domains may be arbitrarily large and quantifiers range over them; validity is semidecidable but not decidable in general."]
    ],
    "05 · Terms, induction, equality & metalevel logic": [
      ["What does a function symbol add to the language?","It builds terms denoting domain elements; an $n$-ary function is interpreted as a total map $D^n\\to D$."],
      ["Why can the Herbrand universe be infinite?","A positive-arity function can be nested indefinitely, producing $a,f(a),f(f(a)),\\ldots$."],
      ["What are the two obligations in ordinary induction?","Prove the base case, then prove $P(n)\\to P(n+1)$ for an arbitrary $n$."],
      ["What changes in structural induction?","Use one base case per atomic constructor and one inductive step per recursive constructor."],
      ["What is the common structural-induction failure?","Omitting a constructor or using the desired claim about the whole object rather than only about its immediate substructures."],
      ["What properties characterize equality?","Reflexivity plus substitutivity/congruence: equal terms may replace one another in predicates and functions."],
      ["Isomorphism versus homomorphism?","An isomorphism is a bijection preserving and reflecting structure. A homomorphism preserves the designated operations/relations but need not be bijective or reflect them."],
      ["State compactness for first-order logic.","A set of sentences is satisfiable iff every finite subset is satisfiable."],
      ["How can first-order logic be complete but undecidable?","Every validity eventually has a proof, but there is no algorithm guaranteed to halt with yes/no on every formula."],
      ["Why is self-reference dangerous in a truth theory?","If a language can encode its own syntax and unrestricted truth predicate, liar-style diagonal sentences can create contradiction."],
      ["Exam checklist for an induction proof?","State the property and domain; cover every base/constructor case; mark the induction hypothesis; use it only on smaller/immediate parts; close the quantified conclusion."]
    ],
    "06 · Worked proof & model drills": [
      ["Classify $p\\to(q\\to p)$.","Valid. If $p$ is false the outer implication is true; if $p$ is true then $q\\to p$ is true for either value of $q$."],
      ["Give a countermodel to $p\\lor q\\models p$.","Set $p=\\text{False}$ and $q=\\text{True}$. The premise is true while the conclusion is false."],
      ["Are $p\\to q$ and $\\neg p\\lor q$ merely consistent or equivalent?","Equivalent: both are false exactly when $p$ is true and $q$ is false."],
      ["Resolve $p\\lor q$ with $\\neg p\\lor r$.","Resolving on $p$ yields $q\\lor r$. Do not retain either resolved literal."],
      ["Show by resolution that $p\\to q, p\\models q$.","CNF for premises and negated conclusion is $(\\neg p\\lor q),p,\\neg q$. Resolve the first with $p$ to get $q$, then with $\\neg q$ to obtain the empty clause."],
      ["In a Fitch proof of $p\\to r$ from $p\\to q$ and $q\\to r$, what is the first structural move?","Open a subproof assuming $p$, use modus ponens twice to derive $q$ and then $r$, and discharge the assumption with implication introduction."],
      ["Countermodel to $\\forall x\\exists yR(x,y)\\models\\exists y\\forall xR(x,y)$?","Use domain $\\{a,b\\}$ with only $R(a,a)$ and $R(b,b)$. Everyone has some related witness, but no one witness is related from every element."],
      ["Translate ‘Every student likes some book’ while allowing different books.","$\\forall x(Student(x)\\to\\exists y(Book(y)\\land Likes(x,y)))$. Moving $\\exists y$ outside would require one common book."],
      ["Why is choosing the same constant for two existential premises illegal?","Each existential may be witnessed by a different domain element. A proof must introduce separate fresh witnesses unless equality is derived."],
      ["Ground $\\forall x(P(x)\\to Q(x))$ over named domain $\\{a,b\\}$.","$(P(a)\\to Q(a))\\land(P(b)\\to Q(b))$, assuming the names exhaust the domain."],
      ["What induction proves a property of every propositional formula?","Structural induction: prove atom cases, then show each connective constructor preserves the property using hypotheses for its immediate subformulas."],
      ["In a binary-tree induction, what must the recursive case assume?","The property for both immediate subtrees, then use both hypotheses to prove it for the parent constructor."],
      ["How do you prove $f(a)=f(c)$ from $a=b$ and $b=c$?","Use transitivity to obtain $a=c$, then function congruence/substitutivity to infer $f(a)=f(c)$."],
      ["How can compactness show there are models of arbitrarily large finite size?","Introduce sentences requiring at least $n$ distinct elements for every $n$. Every finite subset has a sufficiently large finite model, so compactness gives a model satisfying all requirements, necessarily infinite."],
      ["Semantic versus syntactic exam strategy?","For $\\models$, reason with interpretations or a countermodel. For $\\vdash$, exhibit licensed proof steps. Invoke soundness/completeness only when the question connects the two."]
    ]
  } },
  "CS 251": { units:{
    "L1–3 · Foundations & Bitcoin": [
     [`When is a blockchain preferable to a conventional database?`,`When many parties need coordination but no single operator is trusted by all of them. If an acceptable trusted operator exists, a normal replicated database is usually simpler.`],
     [`What does collision resistance let a hash commitment do?`,`It binds the committer to one message: opening the same hash as two distinct messages would produce a collision. A bare hash may still fail to hide a low-entropy message.`],
     [`What is the size of a Merkle inclusion proof for N leaves?`,`O(log N) sibling hashes, plus the left/right direction at each level.`],
     [`What does a valid Merkle inclusion proof establish, and what does it leave unproven?`,`It proves that a leaf belongs to the tree identified by a particular root. It does not prove that the root is authentic or current; consensus or another trusted mechanism must establish that.`],
     [`Define a Bitcoin UTXO.`,`An unspent transaction output: a value plus a locking script that a later transaction may reference and satisfy.`],
     [`How is a Bitcoin transaction fee computed?`,`Sum of input UTXO values minus sum of new output values.`],
     [`What two checks are essential for every Bitcoin input?`,`The referenced output is currently unspent, and the supplied witness satisfies its locking script.`],
     [`Why does a long chain of genesis-difficulty blocks not beat Bitcoin's real chain?`,`Bitcoin chooses greatest cumulative proof of work, not greatest raw block count.`],
     [`What problem did SegWit fix for pre-signed transaction chains?`,`Signature malleability could change a transaction ID without changing its effect, invalidating children. SegWit excludes witness data from the legacy TxID.`],
     [`How does a 2-of-3 escrow limit the arbitrator?`,`Buyer and seller can settle together; in a dispute the arbitrator combines with one party, but cannot take the funds alone.`],
     [`What makes a cross-chain atomic swap atomic?`,`Both chains use the same hash preimage and correctly ordered refund timelocks. Redeeming one side reveals the secret needed for the other; otherwise refunds recover funds.`],
     [`What does theft of an HD wallet's public address-generation key reveal?`,`All derived addresses and balances, destroying privacy, but not normally the spending secret under discrete-log hardness.`],
    ],
    "L4–6 · Consensus": [
     [`Which three properties define Byzantine broadcast?`,`Agreement: honest parties output the same value. Validity: if the sender is honest, they output its value. Termination: every honest party eventually outputs.`],
     [`Synchronous vs asynchronous network?`,`Synchronous means a known message-delay bound always holds. Asynchronous means no known delay bound; eventual delivery alone gives no deadline.`],
     [`State SMR safety using logs.`,`Any two honest client logs at any times are prefix-comparable: one is a prefix of the other.`],
     [`State SMR liveness.`,`A transaction submitted to an honest replica eventually appears in every honest client's log, under the protocol's network and fault assumptions.`],
     [`What is a Sybil attack?`,`One adversary creates many apparent identities. Permissionless consensus therefore weights a scarce resource rather than counting keys.`],
     [`Why can faster proof-of-work blocks weaken security?`,`When the block rate is high relative to propagation delay, honest miners create more competing blocks, split honest work, and make adversarial forks relatively stronger.`],
     [`What does k-deep confirmation mean in Nakamoto consensus?`,`Treat a transaction as confirmed after k blocks follow it. Finality remains probabilistic; reorganization probability decreases with depth under the assumptions.`],
     [`How do dynamic availability and finality differ?`,`Dynamic availability asks whether currently active honest participants can keep extending the ledger as participation changes. Finality asks whether a finalized block can ever be reverted while faults remain below the stated threshold.`],
     [`Why do two 2/3 PoS certificates imply at least 1/3 equivocation if they conflict?`,`Two subsets each of size at least 2/3 must overlap in at least 1/3. Every validator in the overlap signed both conflicts.`],
     [`What does accountable safety add beyond ordinary consensus safety?`,`If conflicting decisions occur, publicly verifiable protocol evidence identifies at least a specified threshold of validators who violated the rules.`],
     [`Why are independent per-validator leader lotteries flawed?`,`A slot can have no leader or several leaders. One stake-partitioned random draw selects exactly one with probability proportional to stake.`],
     [`How do nested chains address the availability–finality dilemma?`,`Maintain an available chain that may reorganize and a slower finalized checkpoint chain that is always its prefix.`],
    ],
    "L7–8 · Ethereum & Solidity": [
     [`EOA versus contract account?`,`An EOA is controlled by a signing key. A contract account contains bytecode and persistent storage and acts when called.`],
     [`Why cannot Solidity mappings provide keys() automatically?`,`The EVM hashes each key and storage slot directly to a location and stores no enumerable key list unless the contract maintains one.`],
     [`Why does every EVM instruction cost gas?`,`To meter scarce computation/storage and ensure execution terminates instead of allowing unbounded loops for free.`],
     [`What is the EIP-1559 effective gas price?`,`min(maxFeePerGas, baseFee + maxPriorityFeePerGas). The base fee is burned and the priority fee rewards the proposer.`],
     [`Why not set Ethereum's block gas limit to a trillion?`,`Validators could not execute, transmit, and store such blocks in time; hardware requirements and state growth would harm liveness and decentralization.`],
     [`Storage vs memory vs calldata?`,`Storage persists across transactions and is expensive. Memory lasts one call. Calldata is immutable external input and is often cheapest to read.`],
     [`What is reentrancy?`,`An external call transfers control before the caller finishes updating its state, letting the callee call back and repeat an operation against stale state.`],
     [`Standard reentrancy defense?`,`Checks–effects–interactions: validate, update all state, then make the external call; add a lock where appropriate.`],
     [`What was wrong with the practice-final ERC-20 transferFrom implementation?`,`It checked that the spender's allowance covered the transfer but never reduced the stored allowance, allowing the same approval to be spent repeatedly.`],
     [`Why can contract Ether balance differ from the sum of internal balances?`,`Ether can be forced or pre-sent without executing the deposit/accounting code. Never equate raw balance with internal liabilities by assumption.`],
     [`Why is blockhash poor lottery randomness?`,`The proposer may withhold or choose among candidate blocks and therefore bias an outcome valuable enough to justify lost rewards.`],
     [`What is the first move in a Solidity exam audit?`,`Write the intended invariant, then trace caller, storage, external calls, and Ether flow line by line.`],
    ],
    "L9–12 · DeFi, MEV & Regulation": [
     [`Custodial vs on-chain-collateralized stablecoin trust?`,`Custodial coins require trust/audits for off-chain reserves and redemption. On-chain collateral is publicly verifiable but still has oracle, volatility, liquidation, and contract risk.`],
     [`Define loan-to-value.`,`Debt value divided by collateral value.`],
     [`When is an overcollateralized position liquidatable?`,`Typically when health factor = threshold-adjusted collateral value / debt value falls below 1.`],
     [`Why can a flash loan be uncollateralized?`,`Borrowing and repayment occur atomically. If principal plus fee is not repaid by transaction end, the entire transaction reverts.`],
     [`Why is a flash loan usually not the root vulnerability?`,`It removes the attacker's capital constraint; the root bug is often a manipulable oracle, instantaneous governance, or shallow liquidity.`],
     [`Constant-product AMM output formula?`,`For reserves (x,y), input Δx, and fee multiplier φ: $\\Delta y = y\\phi\\Delta x/(x+\\phi\\Delta x)$.`],
     [`With no fees or intervening trades, is splitting an AMM trade advantageous?`,`No. Both strategies end at the same final reserves on the same invariant and yield the same total output.`],
     [`What creates sandwich-attack profit?`,`The searcher moves price before a visible victim trade, lets the victim execute within its slippage tolerance, then reverses after it.`],
     [`What is MEV?`,`Value obtained by controlling transaction inclusion, exclusion, or ordering within blocks.`],
     [`How does proposer–builder separation reduce MEV-strategy theft by proposers?`,`The proposer chooses and signs a builder's blinded block header before seeing the full payload, making it harder to copy the builder's transactions and submit a competing block. It does not eliminate MEV.`],
     [`Encrypted mempool: what does it solve and not solve?`,`It hides contents until order is fixed, reducing content-based front-running. It does not by itself guarantee inclusion or prevent decryption collusion/delay.`],
     [`Core idea of control-based decentralization?`,`Analyze who can upgrade, operate, censor, manage treasury, or promise ongoing efforts; the label decentralized does not decide the legal analysis.`],
    ],
    "L13–15 · Alternative L1s & Privacy": [
     [`How does Solana schedule parallel execution?`,`Transactions explicitly list accounts and read/write access, so transactions with nonoverlapping writable state can run in parallel.`],
     [`How does Aptos Block-STM parallelize?`,`Execute optimistically in parallel, detect conflicts, and re-execute conflicting work while preserving the committed order.`],
     [`Why are Move resources useful for assets?`,`A type without copy or drop cannot be accidentally duplicated or discarded through ordinary language operations.`],
     [`Pseudonymity versus unlinkability?`,`Pseudonymity uses persistent aliases that may later be tied to identity. Unlinkability prevents observers from reliably connecting separate actions to one user.`],
     [`Bitcoin common-input heuristic?`,`Inputs spent together are likely controlled by one entity because one transaction needs all corresponding signatures. CoinJoin is an important exception.`],
     [`What does CoinJoin hide?`,`It weakens input-to-output linkage by combining users, especially with equal denominations; later consolidation, change, timing, and network metadata can still deanonymize.`],
     [`What do Confidential Transactions hide?`,`Transaction amounts via homomorphic commitments and range proofs; endpoints and graph structure are generally still visible.`],
     [`Why must confidential outputs have range proofs?`,`Without output nonnegativity/range, an attacker can create a negative hidden output that balances newly minted positive value.`],
     [`What does a Zcash-style shielded transfer aim to hide?`,`Sender, receiver, and amount, unlike amount-only Confidential Transactions.`],
     [`What do completeness, knowledge soundness, and zero knowledge mean for a SNARK?`,`Completeness: an honest proof of a true statement verifies. Knowledge soundness: a prover that convinces the verifier can be treated as knowing a valid witness. Zero knowledge: the proof reveals no information about that witness beyond the public statement.`],
     [`How does a Tornado-style nullifier prevent double spends?`,`Withdrawal reveals a unique value derived from the secret note. The contract rejects a nullifier already recorded without learning which commitment was spent.`],
     [`Why does a zk-SNARK not automatically make a rollup private?`,`The proof may hide its witness while transaction data, senders, recipients, and amounts are still published by the system.`],
    ],
    "L16 · SNARK Construction": [
     [`How does a Merkle tree make a PCP proof succinct?`,`Commit to the long proof by its root, then reveal only the verifier's queried positions with O(log |C|) authentication paths.`],
     [`How does the Fiat–Shamir transform remove verifier interaction?`,`It derives each public verifier challenge by hashing the statement and preceding transcript. This turns suitable public-coin protocols noninteractive in the random-oracle model.`],
     [`What is a polynomial commitment scheme?`,`A binding commitment to a bounded-degree polynomial with short proofs that the committed polynomial evaluates to v at point u.`],
     [`Poly-IOP plus PCS gives what?`,`A succinct argument: polynomial oracles become commitments and verifier queries become opening proofs.`],
     [`What three facts does PLONK prove about a trace?`,`Correct public inputs, valid gate evaluations, and wire-copy consistency under the circuit's prescribed permutation.`],
     [`State the Schwartz–Zippel error bound.`,`Two distinct degree-d polynomials agree at a uniform field point with probability at most d/|F|.`],
     [`What is the vanishing polynomial of Ω?`,`$Z_\\Omega(X)=\\prod_{a\\in\\Omega}(X-a)$; a polynomial is zero on Ω exactly when divisible by it.`],
     [`How do you prove h(Ω) is contained in {0,1}?`,`Invoke ZeroCheck on $h(X)(h(X)-1)$ over Ω.`],
     [`How do you prove h(Ω) is contained in {0,...,7}?`,`Zero-check $\\prod_{j=0}^{7}(h(X)-j)$ over Ω.`],
     [`How do you extend a degree-d PCS to degree 2d+1?`,`Write $g=X^{d+1}g_{high}+g_{low}$, commit to both degree-d parts, open each at u, and verify $v=u^{d+1}v_h+v_l$.`],
     [`What is the trusted-setup failure mode?`,`Knowledge of toxic waste may let a prover forge false proofs. Universal updatable setup is safe if at least one contributor destroys its secret.`],
     [`Exam pattern for proof gadgets?`,`Build a polynomial that vanishes exactly on valid values, then use ZeroCheck; state its degree and soundness bound.`],
    ],
    "L17–19 · Scaling, Bridges & Final Topics": [
     [`What is the payment-channel scaling idea?`,`Lock funds once on-chain, exchange signed balance updates off-chain, and touch the chain only to open, close, or resolve a dispute.`],
     [`Why must Lightning users monitor the chain?`,`A counterparty may broadcast an obsolete commitment. The user or watchtower must submit the revocation remedy during the delay.`],
     [`How do multi-hop Lightning payments stay atomic?`,`Every hop uses the same hash preimage with decreasing timelocks, so revelation completes all hops or refunds unwind them.`],
     [`Why can a rollup process more transactions than L1?`,`L1 verifies a batch proof/dispute and stores compressed data instead of executing every L2 transaction as a full L1 transaction.`],
     [`Validity rollup versus optimistic rollup?`,`Validity: proof required before accepting state. Optimistic: accept provisionally and allow fault proofs during a challenge window.`],
     [`Which three security questions must be evaluated separately for a rollup?`,`Whether state transitions execute correctly, whether users can obtain the data needed to reconstruct state, and whether censorship-resistant submission or forced exit remains possible.`],
     [`Rollup versus validium?`,`Both may use validity proofs; a rollup publishes required state data to L1, while a validium relies on an external data-availability committee.`],
     [`Can a valid proof compensate for withheld rollup data?`,`No. A proof can establish a correct hidden transition without giving users the data needed to reconstruct state or exit.`],
     [`Core lock-and-mint bridge invariant?`,`Wrapped supply on the destination must not exceed assets finalized and locked on the source.`],
     [`Why wait for source-chain finality before bridge minting?`,`A source reorg could erase the lock after destination assets become final, leaving unbacked wrapped tokens.`],
     [`How can flash loans attack DAO governance?`,`Borrow voting power, pass and execute a malicious proposal, extract funds, and repay in one transaction if snapshots and delays are missing.`],
     [`What does account abstraction add?`,`Programmable wallet validation: multisig, passkeys, recovery, batching, session keys, spending limits, and sponsored gas through smart-account logic.`],
    ],
    "Practice Finals · Consensus & Bitcoin": [
     [`A Bitcoin merchant sees a payment in one block. What risk remains, and what should the merchant do?`,`The block can be reorganized or replaced by a heavier conflicting fork. For an irreversible delivery, wait for a confirmation depth appropriate to the payment value and threat model.`],
     [`Why does a chain with more blocks not necessarily win in Bitcoin?`,`Bitcoin selects the valid chain with greatest cumulative proof of work. Many low-difficulty blocks may represent less work than fewer high-difficulty blocks.`],
     [`What network assumption is load-bearing in the course's Nakamoto-consensus analysis?`,`A bound on honest-message propagation delay, always or after stabilization. Without a delay bound, a partition can let incompatible histories grow indefinitely.`],
     [`For two quorums of size q among n validators, what is the minimum intersection?`,`$2q-n$. To ensure the intersection includes an honest validator against at most f Byzantine validators, require $2q-n>f$.`],
     [`If safety must hold for $f<2n/5$, what is the smallest safe finality quorum?`,`Choose $q>7n/10$, so $q=\\lfloor 7n/10\\rfloor+1$. This is the lowest threshold satisfying $2q-n>2n/5$.`],
     [`With the $q>7n/10$ rule, approximately what fraction can stop liveness by withholding?`,`About $3/10$ of validators. More exactly, $n-q+1$ withholding validators leave fewer than q signatures available.`],
     [`If 40% of n validators stop and finality needs 2/3, how many must be ejected before finality resumes?`,`Eject at least $0.1n$: then $0.6n$ active validators are exactly two-thirds of the remaining $0.9n$.`],
     [`If 90% of N validators stop and finality needs 2/3, how many must be ejected?`,`Eject at least $0.85N$: then $0.1N$ active validators are two-thirds of the remaining $0.15N$.`],
     [`Why is an independent leader lottery for every validator flawed even if the expected leader count is one?`,`Independent wins can produce zero leaders or multiple leaders in the same slot. A single random draw over disjoint stake intervals gives exactly one stake-proportional leader.`],
     [`In Byzantine broadcast, what do signatures prevent, and what do they not prevent?`,`They prevent one party from forging another's message. They do not prevent a malicious sender from signing conflicting values or a malicious relay from withholding selectively.`],
     [`Can a stolen Ethereum validation key steal the validator's withdrawal funds directly? What can it do?`,`Not necessarily; withdrawal credentials are separate. It can sign slashable conflicts, causing stake loss and ejection, and contribute that validator's weight to an attack.`],
     [`Why does SIGHASH_NONE let a miner steal transaction inputs?`,`The input signature does not bind the outputs. A miner can preserve the signed inputs, replace all outputs with one paying the miner, and keep the signatures valid.`],
     [`Why can Lightning not replace every Bitcoin base-layer transaction?`,`Channels still need on-chain opening, closing, dispute enforcement, and entry/exit. The base chain is the court that enforces off-chain states.`],
     [`What does a watch-only HD key provide, and what should it not provide?`,`It derives addresses and monitors balances without exposing spending secrets. A related-key signature transformation that preserves one message must not be confused with forging a new spend transaction.`],
    ],
    "Practice Finals · Solidity Traces": [
     [`MovieToken has maxAmount = totalSupply - contractBalance + 1 ether. What are the first four maximum withdrawals?`,`1, 2, 4, and 8 ETH. After each maximum withdrawal, cumulative withdrawals are 1, 3, 7, and 15.`],
     [`How does pre-funding a future contract address break MovieToken?`,`The deployed contract's Ether balance includes the pre-funding but totalSupply does not. Unsigned subtraction underflows, making the withdrawal cap enormous.`],
     [`Why does changing MovieToken's constructor to read contract balance not solve forced-Ether accounting?`,`A helper can later self-destruct to the contract, increasing raw Ether balance without running deposit logic or updating totalSupply.`],
     [`What is the robust repair for balance-derived withdrawal accounting?`,`Store totalWithdrawn explicitly and update it before the external send. Do not infer historical liabilities from address(this).balance.`],
     [`How can a mint loop over-mint when each call checks the supply cap?`,`A receiver callback reenters after each individual mint. Nested calls pass the cap check before suspended outer loops resume and mint their remaining items.`],
     [`Starting at supply 16,370 with a cap of 16,384, how many NFTs can the recursive Hashmasks attack mint?`,`$14+13+\\cdots+1=105$, ending at 16,475.`],
     [`What is the preferred one-line-style defense for the reentrant mint entry point?`,`Apply a standard nonReentrant guard. Replacing safeMint with mint also removes the callback, but sacrifices receiver-safety checks.`],
     [`How does a bidder reduce a marketplace bid just before acceptance?`,`Call the bid-creation function again with the same mapping key and a lower price. If acceptance does not bind an expected price, it reads the overwritten value.`],
     [`Why is XOR unsafe for packing an ERC-20 and ERC-721 address into one key?`,`XOR is commutative: a XOR b equals b XOR a. Swapping typed token arguments reaches the same mapping entry and can turn token amounts into NFT IDs.`],
     [`What is a safe key for a pair of token addresses?`,`Use a nested mapping or a bytes32 hash of a domain-separated, ABI-encoded ordered tuple containing both typed addresses.`],
     [`What is wrong with checking an ERC-20 allowance without changing it?`,`The spender can reuse the same approval repeatedly. transferFrom must decrement the allowance unless it represents an explicitly unlimited approval.`],
     [`Why can WETH's Ether balance exceed the sum of recorded balances even with correct deposits and withdrawals?`,`Ether can be forced into the contract without calling deposit, so raw Ether balance and token liabilities need not be equal.`],
     [`Why is blockhash(block.number) unusable lottery randomness?`,`The EVM returns zero for the current block hash. Even prior block hashes can be influenced by proposers, so valuable lotteries need future verifiable randomness or commit–reveal.`],
     [`Which parties can read a Solidity private mapping?`,`The declaring contract can access it in Solidity, and off-chain observers can inspect raw storage. Another contract cannot access it through the private variable interface.`],
     [`Can an EVM contract query historical event logs?`,`No. Logs are designed for off-chain clients. A contract must store needed data in state or receive it again as input.`],
     [`How can CREATE2 recreate different runtime code at one address?`,`The address commits to initialization code and salt. The same init code can read changed external state and return different runtime bytecode after the old contract self-destructs.`],
    ],
    "Practice Finals · DeFi, Stablecoins & MEV": [
     [`For a no-fee constant-product pool, how much Y does an input Δx return?`,`$\\Delta y=y-xy/(x+\\Delta x)=y\\Delta x/(x+\\Delta x)$. Write the final reserves before simplifying.`],
     [`A pool has k = 25,000 and the target price is 2,000 DAI per ETH. What are its equilibrium reserves?`,`$x=\\sqrt{25{,}000/2{,}000}\\approx3.5355$ ETH and $y=2{,}000x\\approx7{,}071.07$ DAI.`],
     [`In the 2021 LP example, what is the loss relative to holding?`,`The LP position is about 14,142.14 DAI versus 15,000 DAI held, so impermanent loss is about 857.86 USD.`],
     [`Who receives the value represented by no-fee impermanent loss after an external price move?`,`Arbitrageurs, who trade against the stale pool price until the reserve ratio matches the external market.`],
     [`With no fee and no intervening trade, is one AMM swap better than two consecutive half-swaps?`,`Neither. Both paths end at the same reserves and return the same total output.`],
     [`After a sandwich front-run adds εx and the victim adds δx, what fraction of y does the victim receive?`,`$\\delta''=\\delta/((1+\\epsilon)(1+\\epsilon+\\delta))$, less than the no-attack fraction $\\delta/(1+\\delta)$.`],
     [`What limits the optimal sandwich front-run size?`,`The victim's minimum-output or maximum-slippage condition, plus fees and capital costs. Without those costs, the attacker pushes to the victim's acceptance boundary.`],
     [`How can a validator sandwich without owning the front-run asset?`,`Use a flash loan, execute front-run, victim trade, and back-run atomically, then repay from the proceeds.`],
     [`Does MEV-Boost protect a user's swap from sandwiching?`,`No. It auctions block construction and may intensify competition for ordering value. Users need slippage limits or protected/private order flow.`],
     [`A stablecoin loses 10% of reserves. Under pro-rata redemption and no recapitalization, where does price converge?`,`About $0.90 per token. State the issuer/redemption assumption because a run or recapitalization changes the path and result.`],
     [`A USD stablecoin holds x USD and y EUR; after 1 USD buys 1.1z EUR, what is backing per token relative to the old supply?`,`$\\bigl(x+y/(1.1z)\\bigr)/\\bigl(x+y/z\\bigr)$ USD per token.`],
     [`How should a USD stablecoin accept Euro deposits without creating currency mismatch?`,`Convert incoming Euro to USD promptly or fully hedge the FX exposure before minting USD liabilities.`],
     [`In a DeFi exam trace, what permits an uncollateralized flash loan?`,`Repayment is enforced atomically: if principal plus fee is missing at transaction end, all state changes revert.`],
     [`Why are fully on-chain CLOBs uncommon on Ethereum?`,`Order insertion, cancellation, matching, and storage writes are expensive and latency/ordering creates MEV. Specialized chains can optimize the state machine for this workload.`],
    ],
    "Practice Finals · Privacy, Proofs & Rollups": [
     [`Why must confidential-transaction range proofs constrain outputs, not only inputs?`,`Otherwise a negative hidden output can balance a newly created positive output, preserving the sum while inflating spendable value.`],
     [`Why do variable deposit amounts weaken a mixer?`,`The exact amount becomes a fingerprint linking a later withdrawal to its deposit. Fixed denominations place more users in one interchangeable set.`],
     [`If n-1 mixer users reveal their deposit-withdrawal links, what happens to the last user's anonymity?`,`It collapses to one by elimination: the only unmatched deposit corresponds to the only unmatched withdrawal.`],
     [`How can an exchange count two customers with the same balance only once in a naive proof of solvency?`,`Give both customers the same unlabelled balance leaf and Merkle path. Each sees a valid proof, while the liability appears once.`],
     [`How do you prevent duplicate-leaf proof-of-solvency attacks?`,`Commit each leaf to a unique customer identifier/index and balance, and prove that the indexed entries used in the liability sum are distinct.`],
     [`How can a colluding customer lower a field-based liability sum if balances are not range-checked?`,`Accept a leaf representing a negative value modulo p, which cancels part of honest liabilities. Range-prove every balance and prevent modular wraparound.`],
     [`For k mixer withdrawals, when does a 64·ceil(log₂k)-byte accumulator proof save gas under the 2021 exam costs?`,`When $5000+1024\\lceil\\log_2 k\\rceil<20000$, so $k\\le2^{14}=16{,}384$.`],
     [`How do you express a Boolean-value constraint with ZeroCheck?`,`Zero-check $h(X)(h(X)-1)$ on the evaluation domain. It vanishes exactly when every value is 0 or 1.`],
     [`How do you express membership in {0,…,7} with ZeroCheck?`,`Zero-check $\\prod_{j=0}^{7}(h(X)-j)$ on the domain.`],
     [`What proof extends a degree-d PCS to degree 2d+1?`,`Commit to g_high and g_low where $g=X^{d+1}g_{high}+g_{low}$; open both at u and check $v=u^{d+1}v_h+v_l$.`],
     [`Why does an optimistic rollup need transaction signatures in available data?`,`A challenger must authenticate and re-execute a disputed transaction because no validity proof normally establishes every signature before acceptance.`],
     [`Why may a validity rollup omit raw signatures from L1 calldata?`,`The prover can use signatures as private witness and prove their verification. State-reconstruction data still must remain available.`],
     [`Can a centralized rollup coordinator permanently censor an exit?`,`Not in a correctly designed rollup with data availability and an L1 forced-inclusion/escape hatch. Without either property, censorship can trap funds.`],
     [`How can an optimistic rollup defend fault proofs during extreme L1 congestion?`,`Permit a cheap challenge commitment before the deadline and the full proof later; pause or extend finalization while the challenge is pending.`],
     [`How can one zk-rollup post two different valid roots to two settlement chains?`,`Choose different valid transaction batches from the same prior state and prove each transition separately. Validity does not enforce cross-chain uniqueness.`],
     [`What is a simple way to force the same rollup root on two settlement chains?`,`Choose one canonical root sequence; the second chain accepts a root only with a light-client proof that the identical root finalized on the canonical chain.`],
     [`Why is a zk proof without published transaction data not automatically Zcash-level privacy?`,`The coordinator may still see plaintext, and users may lose state recovery. Zero knowledge hides the proof witness only according to the protocol's statement and data design.`],
    ],
    "Practice Finals · Attack Patterns": [
     [`What five-part structure makes a protocol-security answer complete?`,`State the intended invariant; specify the adversary's capabilities; give a concrete attack trace; identify where the invariant fails; propose a repair and state its added cost or assumption.`],
     [`How should you answer a Solidity bug question?`,`Trace exact values and calls, show how the attacker reaches a violating state, then give the smallest invariant-preserving fix.`],
     [`How should you answer a privacy comparison?`,`Name the observer and separately state whether sender, recipient, amount, graph linkage, timing, and network identity are hidden.`],
     [`How should you analyze a bridge?`,`Trace lock, source finality, message verification, mint, burn, and release; check replay protection and who can forge or censor the message.`],
     [`How should you analyze a rollup?`,`Treat validity, data availability, and censorship/exit as separate properties. Solving one does not imply the others.`],
     [`Why can a two-chain zk-rollup hold different valid roots?`,`The coordinator can choose different valid transaction subsets and prove each locally. The system needs one shared batch/root commitment.`],
     [`What is the DePIN concept tested in 2025?`,`Token incentives coordinate real-world infrastructure such as wireless, compute, storage, sensors, or energy; verifying off-chain service creates an oracle problem.`],
     [`What assumption should be explicit in a stablecoin reserve-loss calculation?`,`How the issuer responds—whether it recapitalizes, suspends redemption, or leaves supply outstanding—because backing-per-token depends on that behavior.`],
     [`Why does pausing an ERC-20 not necessarily stop all trading?`,`It prevents on-chain token transfers if implemented correctly, but an exchange may still trade internal custodial claims without moving tokens until withdrawal.`],
     [`What is the cumulative-work exam trap?`,`A chain with more easy blocks can have less total work than a shorter chain of hard blocks; Bitcoin follows cumulative work.`],
     [`What is the forced-Ether exam trap?`,`Contract balance can change without deposit logic, so formulas derived from current balance and internal supply can underflow or miscompute.`],
     [`What should you do when an exam question leaves behavior unspecified?`,`State a reasonable assumption explicitly and give the result under it; many CS 251 questions intentionally test whether you notice the missing condition.`],
    ],
    "Synthesis · Cross-topic scenarios": [
     [`A protocol commits to a bid and reveals it later. What four checks are essential?`,`The commitment must be hiding and binding; reveal must include domain-separated context; deadlines must distinguish commit and reveal phases; non-reveal must have a stated penalty or fallback.`],
     [`Why does a Merkle proof plus a valid signature not prove a transaction is final?`,`They prove membership under one root and authorization by a key. Consensus must still establish that the root belongs to the canonical finalized history.`],
     [`A bridge uses a multisig oracle. What assumptions replace source-chain verification?`,`That enough signers observe finality correctly, remain available, protect keys, and do not collude. Threshold size, rotation, and emergency powers become part of bridge security.`],
     [`A governance token is flash-borrowable. What design blocks one-transaction takeovers?`,`Use voting-power snapshots from an earlier block, proposal and execution delays, quorum, and preferably time-weighted or delegated stake that cannot be borrowed atomically.`],
     [`How do privacy and data availability pull a rollup design in different directions?`,`Users need enough published data to reconstruct state and exit, while privacy limits what is revealed. Encrypt or commit to data while proving validity, but still provide authorized users a durable availability path.`],
     [`When does proof-of-stake slashing provide accountability rather than prevention?`,`Conflicting signatures create public evidence after a safety violation or attempted equivocation. Slashing identifies and penalizes offenders but does not make the conflicting messages impossible.`],
     [`Why can a mathematically sound oracle price still be economically unsafe?`,`The source market may be shallow, delayed, manipulable within one transaction, or mismatched to liquidation timing. Sound arithmetic does not guarantee robust input economics.`],
     [`What links transaction-ordering MEV to consensus design?`,`The party choosing block contents controls ordering value. Builder markets, proposer commitments, encrypted mempools, and inclusion lists redistribute or constrain that power without removing it automatically.`],
     [`What is the invariant-first method for a cross-layer attack?`,`Write the asset/state invariant, trace information and authority across each layer, identify the first layer that accepts an unsupported claim, then repair that boundary and state the new trust assumption.`],
     [`How should a post-quantum migration avoid stranding old assets?`,`Introduce a quantum-resistant spend path before the threat is urgent, provide authenticated migration, define treatment of dormant keys, and avoid exposing vulnerable public keys longer than necessary.`],
    ],
   }},
  "CS 259Q": { units: {
    "01 · Physics of information & overview": [
      ["What makes a physical theory a theory of information processing?","It specifies possible states, allowed transformations, measurements, and how systems compose; computation is constrained by those physical rules."],
      ["Classical bit versus qubit?","A classical pure bit is 0 or 1. A qubit is a normalized vector $\\alpha|0\\rangle+\\beta|1\\rangle$ with $|\\alpha|^2+|\\beta|^2=1$, up to global phase."],
      ["Why is quantum parallelism alone not a speedup?","A circuit may transform a superposition of many inputs, but measurement returns limited classical information. An algorithm must arrange interference so useful outcomes are likely."],
      ["What does unitarity imply about closed-system evolution?","Evolution preserves inner products and is reversible: $U^\\dagger U=I$."],
      ["Why can classical irreversible computation dissipate heat?","Erasing logically distinguishable states is many-to-one and, by Landauer's principle, costs at least $k_B T\\ln 2$ per erased bit in the ideal limit."],
      ["What are the three broad sources of quantum-computing difficulty?","Control errors, unwanted coupling to the environment (decoherence), and the overhead required to detect/correct errors without directly measuring encoded data."],
      ["Global phase versus relative phase?","Multiplying the whole state by $e^{i\\theta}$ changes no measurement statistics. Relative phase between amplitudes can change interference and is observable."],
      ["What is the Born rule?","For state $|\\psi\\rangle$ and projective outcome $|x\\rangle$, the outcome probability is $|\\langle x|\\psi\\rangle|^2$; after measurement the state updates consistently with the outcome."]
    ],
    "02 · States, density operators & distinguishability": [
      ["When do two state vectors represent the same pure state?","When they differ only by a global phase."],
      ["What density operator represents a pure state $|\\psi\\rangle$?","$\\rho=|\\psi\\rangle\\langle\\psi|$. It has rank one and satisfies $\\rho^2=\\rho$ and $\\operatorname{Tr}(\\rho^2)=1$."],
      ["What conditions characterize a density operator?","$\\rho$ is positive semidefinite and $\\operatorname{Tr}\\rho=1$."],
      ["How do you obtain subsystem $A$ from $\\rho_{AB}$?","Take the partial trace: $\\rho_A=\\operatorname{Tr}_B(\\rho_{AB})$."],
      ["What does Schmidt decomposition say?","Every bipartite pure state can be written $|\\psi\\rangle=\\sum_i\\sqrt{\\lambda_i}|i_A\\rangle|i_B\\rangle$ with orthonormal Schmidt bases and $\\lambda_i\\ge0$, $\\sum_i\\lambda_i=1$."],
      ["How does Schmidt rank detect pure-state entanglement?","A bipartite pure state is separable exactly when its Schmidt rank is one."],
      ["Trace distance operational meaning?","$D(\\rho,\\sigma)=\\tfrac12\\|\\rho-\\sigma\\|_1$ determines optimal binary distinguishing advantage; with equal priors, $p_{\\rm guess}=\\tfrac12(1+D)$."],
      ["State the pure-state fidelity formula.","For pure states, $F(|\\psi\\rangle,|\\phi\\rangle)=|\\langle\\psi|\\phi\\rangle|^2$ under the squared-fidelity convention."],
      ["What is purification?","Any mixed $\\rho_A$ can be represented as the reduced state of a larger pure state $|\\psi\\rangle_{AR}$; different purifications are related by an isometry on the purifying system."],
      ["Why does ensemble decomposition not identify an objective hidden preparation?","The same density operator can have many decompositions into pure-state ensembles, and no measurement on the system distinguishes which decomposition was used."]
    ],
    "03 · POVMs, channels & open systems": [
      ["What is a POVM?","Positive operators $\\{E_y\\}$ satisfying $\\sum_y E_y=I$; outcome $y$ occurs with probability $\\operatorname{Tr}(E_y\\rho)$."],
      ["How do Kraus operators describe a channel?","$\\mathcal E(\\rho)=\\sum_k A_k\\rho A_k^\\dagger$ with $\\sum_k A_k^\\dagger A_k=I$ for trace preservation."],
      ["What properties define a quantum channel?","It is completely positive and trace preserving (CPTP). Complete positivity is required even when the input is entangled with an untouched reference."],
      ["State Stinespring dilation.","Every quantum channel can be realized by adjoining an environment, applying an isometry/unitary, and tracing out the environment."],
      ["What is the Choi matrix and why is it useful?","$J(\\mathcal E)=(\\mathcal E\\otimes I)(|\\Phi\\rangle\\langle\\Phi|)$. The map is completely positive iff $J\\ge0$, and trace preservation is a partial-trace condition."],
      ["What does the depolarizing channel do?","It replaces the state by the maximally mixed state with some probability: $\\mathcal E(\\rho)=(1-p)\\rho+pI/d$ under one common convention."],
      ["Amplitude damping versus dephasing?","Amplitude damping models energy relaxation such as $|1\\rangle\\to|0\\rangle$; dephasing suppresses off-diagonal coherence without changing computational-basis populations."],
      ["What is a Lindblad master equation for?","It gives continuous-time Markovian open-system evolution: a Hamiltonian commutator plus dissipative jump terms that preserve complete positivity and trace."],
      ["Why can a spin echo undo some dephasing?","A pulse reverses phase accumulation from slow, approximately static frequency offsets, causing phases to refocus. It does not undo arbitrary fast noise or energy loss."],
      ["What is data processing for trace distance?","A channel cannot make states more distinguishable: $D(\\mathcal E(\\rho),\\mathcal E(\\sigma))\\le D(\\rho,\\sigma)$."]
    ],
    "04 · Entanglement, Bell & protocols": [
      ["What is a separable mixed state?","$\\rho_{AB}=\\sum_i p_i\\,\\rho_A^{(i)}\\otimes\\rho_B^{(i)}$. A state not expressible this way is entangled."],
      ["State the CHSH classical and quantum bounds.","Local hidden-variable strategies satisfy $|S|\\le2$; quantum mechanics reaches Tsirelson's bound $2\\sqrt2$."],
      ["Why does Bell violation not enable faster-than-light signaling?","Each party's local marginal distribution is independent of the distant measurement choice, even though joint correlations violate a Bell inequality."],
      ["What resources does teleportation consume and transmit?","One shared ebit plus two classical bits transmit an unknown qubit state; no physical copy of the original remains."],
      ["What resources does superdense coding use?","One shared ebit and transmission of one qubit communicate two classical bits."],
      ["State the no-cloning argument in one line.","If a unitary cloned both $|\\psi\\rangle$ and $|\\phi\\rangle$, inner-product preservation would require $\\langle\\psi|\\phi\\rangle=\\langle\\psi|\\phi\\rangle^2$, impossible for distinct nonorthogonal states."],
      ["Why does BB84 reveal eavesdropping?","An eavesdropper who measures without knowing the basis disturbs incompatible-basis states, producing errors detected in a public sample."],
      ["Monogamy of entanglement intuition?","If $A$ is maximally entangled with $B$, it cannot also be entangled with an independent $C$; strong quantum correlations limit shareability."],
      ["What is entanglement swapping?","A Bell measurement on one member of each of two entangled pairs can entangle the two systems that never interacted, conditioned on the result."],
      ["What does partial transpose test?","A negative partial transpose proves entanglement. For $2\\times2$ and $2\\times3$ systems, positivity of the partial transpose is also sufficient for separability."]
    ],
    "05 · Reversible & quantum circuits": [
      ["Why must a reversible classical gate be a permutation?","Distinct input basis states must map to distinct outputs so the operation has an inverse."],
      ["What does the Toffoli gate compute?","$(a,b,c)\\mapsto(a,b,c\\oplus ab)$. It is universal for reversible classical computation."],
      ["Why is uncomputation necessary?","Temporary garbage can remain entangled with the output and destroy interference. Copy the desired classical result when allowed, then run the workspace computation backward."],
      ["What does the Hadamard gate do?","$H|0\\rangle=|+\\rangle$ and $H|1\\rangle=|-\\rangle$; it changes between computational and $X$ bases."],
      ["What makes a gate set approximately universal?","Finite products from the set can approximate every target unitary to arbitrary accuracy, often using arbitrary one-qubit gates plus any entangling two-qubit gate."],
      ["What does the Solovay–Kitaev theorem guarantee?","For suitable finite universal gate sets closed under inverses, an arbitrary unitary can be approximated to error $\\epsilon$ with polylogarithmic gate count in $1/\\epsilon$."],
      ["How does phase kickback work?","If an eigenstate $|u\\rangle$ satisfies $U|u\\rangle=e^{2\\pi i\\phi}|u\\rangle$, controlled-$U$ places that phase on the control amplitude."],
      ["How do you verify a circuit identity efficiently?","Track basis states or Pauli conjugation when possible, respect right-to-left matrix order, and test phases rather than checking only classical truth tables."],
      ["Why is measurement generally irreversible?","It discards coherence between outcome subspaces and records a classical result; without the environment record and premeasurement state, the map cannot be inverted."],
      ["What is circuit depth?","The minimum number of sequential layers after gates on disjoint qubits are parallelized; it captures time under a parallel gate model."]
    ],
    "06 · QFT, Shor, Grover & complexity": [
      ["Define the quantum Fourier transform over $\\mathbb Z_N$.","$|x\\rangle\\mapsto\\frac1{\\sqrt N}\\sum_{y=0}^{N-1}e^{2\\pi ixy/N}|y\\rangle$."],
      ["What is phase estimation's output?","An $m$-bit estimate of eigenphase $\\phi$ given controlled powers of $U$ and an eigenstate $|u\\rangle$."],
      ["How does period finding lead to factoring?","For random $a$ coprime to $N$, find the order $r$ of $a\\bmod N$. If $r$ is even and $a^{r/2}\\not\\equiv-1$, then $\\gcd(a^{r/2}\\pm1,N)$ gives nontrivial factors."],
      ["Why does Shor need continued fractions?","A QFT measurement approximates a rational $s/r$; continued fractions recover the small denominator $r$ when the approximation is accurate enough."],
      ["What is Grover's query complexity for one marked item among $N$?","$\\Theta(\\sqrt N)$ oracle queries, and this is asymptotically optimal in the black-box model."],
      ["What two reflections make a Grover iteration?","A phase flip on marked states and a reflection about the initial uniform state; together they rotate amplitude toward the marked subspace."],
      ["How many Grover iterations for $M$ marked items?","About $\\frac{\\pi}{4}\\sqrt{N/M}$ when $M$ is known and small relative to $N$."],
      ["What is QMA?","Problems whose yes instances have polynomial-size quantum witnesses verified with bounded error by a polynomial-time quantum verifier."],
      ["BQP versus QMA?","BQP is efficient bounded-error quantum computation without a witness. QMA adds an untrusted quantum proof and is the quantum analogue of NP-style verification."],
      ["What is Hamiltonian simulation?","Approximate $e^{-iHt}$ with a quantum circuit. Its cost depends on time, error, and structure such as locality or sparsity."]
    ],
    "07 · Quantum error correction": [
      ["Why can quantum errors be corrected despite no-cloning?","Encode one logical state into an entangled subspace and measure an error syndrome that reveals the error class without revealing logical amplitudes."],
      ["State the Knill–Laflamme condition.","A code with projector $P$ corrects errors $\\{E_a\\}$ iff $PE_a^\\dagger E_bP=c_{ab}P$ for all $a,b$."],
      ["What does code distance $d$ mean?","The minimum weight of a Pauli operator that acts nontrivially on the logical code space; the code corrects up to $\\lfloor(d-1)/2\\rfloor$ arbitrary qubit errors."],
      ["What is a stabilizer code?","The joint $+1$ eigenspace of an abelian Pauli subgroup not containing $-I$. Independent generators provide syndrome checks."],
      ["How many logical qubits does an $n$-qubit stabilizer with $r$ independent generators encode?","$k=n-r$ logical qubits."],
      ["What are CSS codes built from?","Two compatible classical binary linear codes, giving separate $X$-type and $Z$-type stabilizer checks."],
      ["What is a logical Pauli operator?","A Pauli in the stabilizer normalizer that preserves the code space but is not itself a stabilizer, so it acts nontrivially on encoded information."],
      ["Why repeat syndrome extraction?","Measurements and ancillas can be faulty. Repetition over space-time lets the decoder distinguish data errors from measurement errors."],
      ["Surface-code logical operators?","Strings of Pauli operators connecting appropriate boundaries or wrapping nontrivial topology; code distance is the shortest such undetectable string."],
      ["What is the threshold theorem?","Below a physical error-rate threshold and under stated noise/control assumptions, arbitrarily long computation is possible with polylogarithmic overhead in target reliability."]
    ],
    "08 · Quantum Shannon theory": [
      ["Define von Neumann entropy.","$S(\\rho)=-\\operatorname{Tr}(\\rho\\log\\rho)$, the Shannon entropy of $\\rho$'s eigenvalues."],
      ["What is Schumacher compression?","Many copies of a quantum source with density operator $\\rho$ can be faithfully compressed to about $S(\\rho)$ qubits per signal, but not below that asymptotically."],
      ["What is a typical subspace?","For many i.i.d. states, almost all probability lies in a subspace of dimension about $2^{nS(\\rho)}$ whose eigenvalues are nearly uniform on an exponential scale."],
      ["State subadditivity.","$S(AB)\\le S(A)+S(B)$, with equality exactly for product states."],
      ["State strong subadditivity.","$S(ABC)+S(B)\\le S(AB)+S(BC)$, equivalently conditional mutual information $I(A:C|B)\\ge0$."],
      ["What is the Holevo bound?","For ensemble $\\{p_x,\\rho_x\\}$, accessible classical information is at most $\\chi=S(\\sum_xp_x\\rho_x)-\\sum_xp_xS(\\rho_x)$."],
      ["Why can quantum conditional entropy be negative?","For entangled states, $S(A|B)=S(AB)-S(B)$ may be negative; the negativity reflects entanglement and has operational meaning in protocols."],
      ["Classical capacity versus quantum capacity?","Classical capacity is the optimal reliable classical communication rate; quantum capacity is the coherent qubit/entanglement transmission rate and can vanish even when classical capacity is positive."],
      ["What is coherent information?","$I(A\\rangle B)=-S(A|B)=S(B)-S(AB)$; regularized optimized coherent information characterizes quantum capacity in general."],
      ["What is decoupling's central idea?","If a subsystem becomes nearly independent of the reference, its information has moved into the complementary subsystem, enabling protocols for communication, merging, and entanglement generation."]
    ],
    "09 · Anyons & topological computation": [
      ["Bosons, fermions, and anyons differ how under exchange?","In 3D identical particles give symmetric or antisymmetric states. In 2D, exchanges form the braid group and can act by general phases or matrices."],
      ["What is an anyon fusion rule?","An algebraic rule $a\\times b=\\sum_cN_{ab}^c\\,c$ listing possible total topological charges and multiplicities."],
      ["What is a fusion space?","The Hilbert space of consistent fusion paths for a set of anyons with fixed total charge; its dimension can grow exponentially and encode qubits."],
      ["What does an $F$ move do?","It changes the association order/fusion basis, such as from $(a\\times b)\\times c$ to $a\\times(b\\times c)$, without physically braiding particles."],
      ["What does an $R$ move do?","It represents exchanging two adjacent anyons in a basis where their fusion channel is definite."],
      ["Why do the pentagon and hexagon equations matter?","They enforce consistency among different sequences of reassociation and braiding operations."],
      ["Fibonacci anyon fusion rule?","$\\tau\\times\\tau=1+\\tau$; repeated $\\tau$ anyons have Fibonacci-growing fusion-space dimension."],
      ["Why is topological encoding robust?","Logical information is stored nonlocally in global fusion degrees of freedom, so sufficiently local perturbations cannot easily distinguish or alter it."],
      ["How does braiding implement a gate?","A braid word acts through the anyon model's braid-group representation on the encoded fusion space."],
      ["Are Fibonacci braids computationally universal?","Their braid representation is dense enough for approximating arbitrary encoded unitaries, while measurement/fusion supplies initialization and readout."],
      ["What error remains in topological computation?","Thermal anyon creation, motion, imperfect measurement, leakage, and finite-separation effects still require active control and error correction."],
      ["Worked-problem workflow for anyon braids?","Choose a fusion-tree basis, insert $F$ moves until the braided pair is adjacent, apply the channel-dependent $R$, then undo the basis changes."]
    ],
    "10 · Worked calculations & circuit drills": [
      ["What is the reduced state of either qubit of $|\\Phi^+\\rangle=(|00\\rangle+|11\\rangle)/\\sqrt2$?","$I/2$. Tracing out either side removes the cross terms and leaves equal probabilities on $|0\\rangle$ and $|1\\rangle$."],
      ["Equal-prior pure states have overlap magnitude $c$. What is optimal discrimination success?","Helstrom gives $p_{\\rm succ}=\\tfrac12(1+\\sqrt{1-c^2})$. Orthogonal states give 1; identical states give $1/2$."],
      ["Apply complete dephasing to $\\rho=\\begin{pmatrix}a&b\\\\b^*&d\\end{pmatrix}$.","The output is $\\operatorname{diag}(a,d)$. Populations remain while off-diagonal coherence vanishes."],
      ["Amplitude damping with probability $\\gamma$ acts on $|1\\rangle$. What is the output density matrix?","$(1-\\gamma)|1\\rangle\\langle1|+\\gamma|0\\rangle\\langle0|$: decay is probabilistic after the environment is traced out."],
      ["What is $QFT_4|1\\rangle$?","$\\tfrac12(|0\\rangle+i|1\\rangle-|2\\rangle-i|3\\rangle)$ using phase $e^{2\\pi i y/4}$."],
      ["Use order finding to factor 15 with $a=2$.","The order is $r=4$ because $2^4\\equiv1\\pmod{15}$. Then $\\gcd(2^{2}-1,15)=3$ and $\\gcd(2^{2}+1,15)=5$."],
      ["Phase estimation receives eigenphase $\\phi=3/8$ with three counting qubits. What ideal bit string appears?","`011`, because $3/8=0.011_2$ is exactly representable with three fractional bits."],
      ["About how many Grover iterations search 1024 items for one marked item?","$\\lfloor(\\pi/4)\\sqrt{1024}\\rfloor\\approx25$ iterations."],
      ["How does the Grover count change for four marked items among 1024?","Use $\\frac{\\pi}{4}\\sqrt{N/M}$, giving about $\\frac{\\pi}{4}\\sqrt{256}\\approx12.6$, so roughly 12–13 iterations."],
      ["For the three-qubit bit-flip code, what syndrome identifies an $X$ error on the middle qubit?","With stabilizers $Z_1Z_2$ and $Z_2Z_3$, both checks flip sign, giving syndrome $(-1,-1)$."],
      ["What condition makes CSS $X$- and $Z$-type stabilizers commute?","Their binary support vectors must have even overlap, equivalently the relevant classical parity-check products vanish mod 2."],
      ["State the quantum Singleton bound for an $[[n,k,d]]$ code.","$n-k\\ge2(d-1)$. It limits how much redundancy is required for distance $d$."],
      ["A qubit has eigenvalues $p$ and $1-p$. What is its entropy?","$S(\\rho)=H_2(p)=-p\\log_2p-(1-p)\\log_2(1-p)$. It is 0 at $p=0,1$ and 1 at $p=1/2$."],
      ["What is the mutual information $I(A:B)$ of a Bell pair?","$S(A)+S(B)-S(AB)=1+1-0=2$ bits."],
      ["A source has entropy $S(\\rho)=0.6$ qubits/signal. Roughly how large is the typical subspace for 100 signals?","About $2^{100\\cdot0.6}=2^{60}$ dimensions, up to subexponential factors and a small atypical probability."],
      ["What is the fusion-space dimension of $n$ Fibonacci anyons with fixed total charge?","It follows the Fibonacci recurrence because $\\tau\\times\\tau=1+\\tau$; the exact index depends on the chosen total charge, but growth is asymptotically $\\varphi^n$."],
      ["How do you braid nonadjacent anyons in a fusion-tree basis?","Apply $F$ moves to a basis where the pair fuses first, apply the appropriate $R$ phase/matrix, then apply inverse $F$ moves."],
      ["In teleportation, which corrections correspond to Alice's two measurement bits?","For outcomes `00,01,10,11`, Bob applies $I,X,Z,XZ$ respectively, up to convention/global phase."],
      ["Why does measuring a stabilizer syndrome not reveal $\\alpha,\\beta$ of an encoded qubit?","All logical codewords share the same stabilizer eigenvalues; the syndrome distinguishes error subspaces while acting identically on logical amplitudes."],
      ["How do you check a proposed Kraus representation?","Verify $\\sum_k A_k^\\dagger A_k=I$ for trace preservation, compute its action on a general density matrix or basis operators, and confirm the intended channel parameters." ]
    ]
  } }
};
