"use strict";

CARD_DATA["CompTIA A+ Core 1"] = { units: {
  "1.1 · Mobile hardware replacement": [
    ["Which replaceable laptop memory form factor is most common?","SODIMM. It is shorter than a desktop DIMM; DDR4 SODIMMs have 260 pins and DDR5 SODIMMs have 262 pins."],
    ["What should you verify before replacing a laptop battery?","Exact model/chemistry, voltage and connector, physical fit, warranty procedure, and whether the battery is swollen or otherwise hazardous."],
    ["What is the safe response to a swollen lithium battery?","Power down, stop charging and using it, do not puncture or bend it, isolate it from combustibles, and follow approved replacement and recycling procedures."],
    ["Which laptop storage forms are commonly replaceable?","A 2.5-inch SATA drive and an M.2 card are common. Verify whether an M.2 slot supports SATA, PCIe/NVMe, the card key, and its length."],
    ["What is the most important Wi-Fi-card detail during laptop reassembly?","Reconnect the antenna leads to the documented main/aux terminals and route them correctly; the antennas are commonly placed around the display bezel."],
    ["Why photograph cable routing before mobile-device disassembly?","Small ribbon, antenna, camera, and microphone cables have precise routing and connector order; a photo reduces damage and reassembly errors."],
    ["Which mobile components create privacy or security concerns?","Camera/webcam, microphone, biometrics, NFC scanner features, and wireless antennas because they collect identity, audio, video, proximity, or network data."],
    ["What precautions apply when replacing mobile hardware?","Back up data, power down, disconnect power/battery when safe, use ESD controls and correct tools, track screw locations, and follow manufacturer procedures." ]
  ],
  "1.2 · Mobile accessories & connectivity": [
    ["What does USB-C describe, and what does it not guarantee?","USB-C describes a reversible connector. It does not by itself guarantee a particular USB speed, Power Delivery, DisplayPort alt mode, or Thunderbolt."],
    ["What is Lightning?","Apple's reversible connector used on many older iPhones, iPads, and accessories; newer Apple devices increasingly use USB-C."],
    ["What is NFC best suited for?","Very-short-range tap interactions such as payment, pairing bootstrap, badges, and tag reading."],
    ["What is the normal Bluetooth pairing sequence?","Enable Bluetooth, make the accessory discoverable, select it, confirm/enter the PIN or code, and test the connection."],
    ["How do tethering and a mobile hotspot differ?","Both share a device's cellular data. Tethering may use USB or Bluetooth; a hotspot normally creates a Wi-Fi network."],
    ["Active versus passive stylus?","An active stylus uses electronics/power and may support pressure, hover, palm rejection, or buttons. A passive stylus behaves more like a finger."],
    ["Docking station versus port replicator?","Both expand connectivity. A dock typically adds broader power/display/peripheral capabilities; a port replicator primarily exposes more ports."],
    ["Trackpad, track point, and drawing pad?","A trackpad is a touch surface, a track point is a small keyboard pointing stick, and a drawing pad/digitizer provides pen-oriented input." ]
  ],
  "1.3 · Mobile networks, MDM & synchronization": [
    ["What do 3G, 4G/LTE, and 5G identify?","Generations of cellular data technology. Actual coverage, frequency, latency, and speed depend on carrier and location."],
    ["SIM versus eSIM?","A SIM is a removable subscriber module; an eSIM is provisioned electronically in embedded hardware. Both associate service credentials with a carrier account."],
    ["How should you troubleshoot missing cellular data first?","Check airplane mode and cellular-data settings, signal/coverage, account and data cap, SIM/eSIM state, carrier outage, and restart/update before resetting network settings."],
    ["GPS versus cellular location?","GPS/GNSS derives position from satellite signals. Cellular and Wi-Fi observations can provide or assist location, especially indoors or for faster initial fixes."],
    ["What does MDM do?","Mobile device management enrolls devices, pushes configuration, enforces policy, deploys corporate apps/certificates, inventories devices, and can remotely lock or wipe them."],
    ["Corporate-owned versus BYOD management concern?","Corporate devices allow stronger control. BYOD requires separating organizational data and policy from the user's personal ownership and privacy."],
    ["Which data commonly synchronizes on mobile devices?","Mail, calendars, contacts, business applications, files, and cloud storage, subject to account, policy, connectivity, and data-cap settings."],
    ["Why check data caps before large synchronization?","Cellular plans may throttle or charge for usage; large cloud backups, updates, or media sync can consume the allowance quickly." ]
  ],

  "2.1 · TCP, UDP, ports & protocols": [
    ["TCP versus UDP?","TCP is connection-oriented and provides ordered reliable byte delivery with flow/congestion control. UDP is connectionless with low overhead and no built-in delivery or ordering guarantee."],
    ["FTP ports and purpose?","TCP 20/21. FTP transfers files but is not secure by default; SFTP instead uses SSH on port 22."],
    ["SSH and Telnet ports?","SSH uses TCP 22 and encrypts remote sessions. Telnet uses TCP 23 and sends traffic without modern transport security."],
    ["SMTP port and purpose?","TCP 25 for mail transfer between servers; authenticated client submission commonly uses 587."],
    ["DNS port and transport?","Port 53, commonly UDP for ordinary queries and TCP for larger responses, transfers, or fallback."],
    ["DHCP ports?","UDP 67 for the server and UDP 68 for the client."],
    ["HTTP and HTTPS ports?","HTTP uses TCP 80; HTTPS uses TCP 443 with TLS."],
    ["POP3 and IMAP ports?","POP3 uses TCP 110 and commonly downloads mail; IMAP uses TCP 143 and synchronizes server-side mail state. Secure variants commonly use 995 and 993."],
    ["NetBIOS/NetBT ports?","Ports 137–139, associated with legacy Windows naming/session services over TCP/IP."],
    ["LDAP port and purpose?","TCP/UDP 389 for directory queries; LDAPS commonly uses TCP 636."],
    ["SMB/CIFS port?","TCP 445 for Windows-style file and printer sharing."],
    ["RDP port?","TCP/UDP 3389 for Microsoft Remote Desktop."],
    ["Why is memorizing only a port number insufficient?","Exam scenarios also test the service purpose, whether it is secure, and whether TCP, UDP, or both are expected."],
    ["Which protocols in the objective commonly use UDP?","DNS commonly uses UDP 53 and DHCP uses UDP 67/68; TCP is used when DNS requires reliable larger transfers." ]
  ],
  "2.2 · Wireless technologies": [
    ["2.4 GHz versus 5 GHz Wi-Fi?","2.4 GHz generally travels farther and penetrates better but has fewer channels/more interference. 5 GHz offers more capacity/channels but usually shorter range."],
    ["What does the 6 GHz band add?","More clean spectrum and wide channels for supported Wi-Fi 6E/7 devices, with shorter-range/compatibility considerations."],
    ["Common nonoverlapping 2.4 GHz channels in North America?","1, 6, and 11 when using 20 MHz channels."],
    ["Why does channel width matter?","Wider channels can increase throughput but consume more spectrum and overlap/interfere with more neighboring networks."],
    ["What bands do Wi-Fi 4, 5, 6/6E, and 7 use?","Wi-Fi 4: 2.4/5 GHz; Wi-Fi 5: 5 GHz; Wi-Fi 6: 2.4/5 GHz; 6E adds 6 GHz; Wi-Fi 7 can use 2.4/5/6 GHz."],
    ["Bluetooth's primary role?","Short-range personal-area connectivity for peripherals, audio, input, and low-power device communication."],
    ["NFC versus RFID?","NFC is very-short-range two-way communication and a subset/relative of RFID concepts; RFID broadly identifies tags by radio and may work over longer ranges."],
    ["What should channel selection account for?","Regulatory region, band, channel width, neighboring APs, interference, client support, and desired coverage/capacity." ]
  ],
  "2.3 · Networked hosts & services": [
    ["DNS server role?","Translate names to records such as IP addresses and service information."],
    ["DHCP server role?","Lease IP configuration including address, mask, gateway, DNS, and other options."],
    ["File, print, web, and mail server roles?","They provide shared storage, queued printer access, HTTP content/applications, and message transport/storage respectively."],
    ["Syslog server role?","Receive and centralize event/log messages from systems and network devices."],
    ["What does AAA mean?","Authentication verifies identity, authorization determines allowed actions, and accounting records use/activity."],
    ["Database server role?","Store, query, and manage structured application data; applications normally access it through a database service rather than raw files."],
    ["NTP server role?","Synchronize clocks, which supports logs, certificates, authentication, and event correlation."],
    ["Spam gateway, UTM, load balancer, and proxy?","A spam gateway filters mail; UTM combines security controls; a load balancer distributes service requests; a proxy intermediates client or server traffic."],
    ["What is SCADA?","Supervisory control and data acquisition: legacy/embedded operational technology used to monitor and control industrial processes."],
    ["Why are IoT and embedded devices special support risks?","They may have limited interfaces, long lifetimes, weak update support, default credentials, and safety/availability consequences." ]
  ],
  "2.4 · DNS, DHCP, VLANs & VPNs": [
    ["What do DNS A and AAAA records contain?","A maps a name to IPv4; AAAA maps a name to IPv6."],
    ["What do CNAME and MX records do?","CNAME aliases one DNS name to another; MX identifies mail exchangers for a domain."],
    ["What is a DNS TXT record used for?","Arbitrary text, commonly domain verification and email controls such as SPF, DKIM-related data, and DMARC policies."],
    ["SPF, DKIM, and DMARC in one sentence each?","SPF authorizes sending sources; DKIM signs mail; DMARC states alignment/policy and reporting using SPF/DKIM results."],
    ["DHCP scope, lease, reservation, and exclusion?","Scope is the address pool/config; lease is a time-limited assignment; reservation maps a client to a fixed address; exclusion prevents pool assignment of selected addresses."],
    ["What is a VLAN?","A logical Layer-2 broadcast domain configured on switches; routing is required between VLANs."],
    ["What is a VPN?","An authenticated encrypted tunnel over another network, used for remote access or site-to-site connectivity."],
    ["Why is a DHCP reservation often preferred for printers?","It provides a stable address while keeping configuration centrally managed and avoiding accidental duplicate statics." ]
  ],
  "2.5 · Network hardware": [
    ["Switch versus router?","A switch forwards frames within a Layer-2 network using MAC addresses; a router forwards packets between IP networks."],
    ["Managed versus unmanaged switch?","Managed switches expose configuration/monitoring such as VLANs, STP, QoS, and port status; unmanaged switches provide basic forwarding."],
    ["Access point role?","Bridge wireless clients onto a wired network and manage radio association/security."],
    ["Patch panel role?","Passive termination/organization point for permanent cable runs; patch cords connect it to switch ports."],
    ["Firewall role?","Permit or deny traffic according to security policy and connection/address/application information."],
    ["PoE switch versus injector?","Both provide power over Ethernet. A PoE switch powers many ports; an injector adds power to one link between a non-PoE switch and powered device."],
    ["Cable modem, DSL modem, and ONT?","Cable modem terminates coax service, DSL modem uses telephone copper, and an ONT converts provider fiber service to customer interfaces."],
    ["What identifies a NIC at Layer 2?","Its MAC address; IP configuration is a separate Layer-3 identity and can change." ]
  ],
  "2.6 · IP addressing": [
    ["IPv4 versus IPv6 size/notation?","IPv4 is 32-bit dotted decimal; IPv6 is 128-bit hexadecimal separated by colons."],
    ["Private IPv4 ranges?","10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16."],
    ["IPv4 and IPv6 loopback?","127.0.0.1 and ::1."],
    ["What does an IPv4 169.254.x.x address indicate?","APIPA/link-local self-assignment, usually because a DHCP lease was unavailable; it normally cannot route beyond the local subnet."],
    ["Static versus dynamic address?","Static is manually/persistently configured; dynamic is assigned through DHCP for a lease period."],
    ["Subnet mask/prefix purpose?","Identify which address bits describe the local network versus host so the device knows whether to send directly or through a router."],
    ["Default gateway purpose?","The local router used to reach destinations outside the host's subnet."],
    ["IPv6 link-local prefix?","FE80::/10; link-local addresses work only on the local link and commonly support neighbor/router operations." ]
  ],
  "2.7 · Internet connections & network types": [
    ["Satellite Internet tradeoff?","Broad geographic reach but high propagation latency, weather/obstruction sensitivity, and possible data limits."],
    ["Fiber Internet tradeoff?","High capacity and low latency, but availability and installation cost depend on provider buildout."],
    ["Cable versus DSL?","Cable uses coax and often shares neighborhood capacity; DSL uses telephone copper and performance depends strongly on distance/line quality."],
    ["Cellular and WISP access?","Cellular uses carrier mobile networks; a WISP provides fixed wireless service from provider radios/towers to customer equipment."],
    ["LAN, WLAN, and WAN?","LAN is a local network; WLAN is a wireless LAN; WAN connects geographically separated networks."],
    ["PAN and MAN?","PAN covers a person's short-range devices; MAN covers a metropolitan/city-scale area."],
    ["What is a SAN?","A storage area network providing block-level storage connectivity between servers and storage systems."],
    ["Which connection is most sensitive to distance from a central office?","Traditional DSL over copper." ]
  ],
  "2.8 · Network tools": [
    ["Crimper versus punchdown tool?","A crimper attaches modular plugs to patch cable; a punchdown tool seats conductors into IDC terminals on jacks/patch panels."],
    ["Cable stripper purpose?","Remove the jacket without damaging conductors before termination."],
    ["Cable tester purpose?","Check continuity and wire map for opens, shorts, reversals, split/miswired pairs, and related faults."],
    ["Toner probe purpose?","A tone generator places a signal on a cable and the probe traces/identifies the run."],
    ["Wi-Fi analyzer purpose?","Measure SSIDs, channels, signal, utilization/interference clues, and RF coverage."],
    ["Loopback plug purpose?","Send an interface's output back to its input to test the port and protocol stack path."],
    ["Network tap purpose?","Provide a copy of network traffic to an analyzer/monitor without relying on the endpoint."],
    ["Which tool finds an unlabeled cable rather than proving its pin map?","A toner probe identifies the run; a cable tester verifies electrical mapping." ]
  ],

  "3.1 · Displays": [
    ["LCD versus OLED?","LCD pixels modulate a separate backlight; OLED pixels emit their own light and can turn fully off for deep black."],
    ["TN, IPS, and VA strengths?","TN: fast/inexpensive; IPS: color/viewing angles; VA: strong LCD contrast."],
    ["Mini-LED versus OLED?","Mini-LED is a dense local-dimming backlight behind an LCD; OLED is self-emissive at each pixel."],
    ["What does a legacy LCD inverter do?","Convert low-voltage DC to higher-voltage AC for a CCFL backlight."],
    ["Display versus digitizer?","The display creates the image; the digitizer detects touch or stylus position."],
    ["Pixel density unit?","Pixels per inch, or PPI."],
    ["Refresh rate unit and meaning?","Hertz; the number of display refreshes per second."],
    ["Why use an LCD's native resolution?","It maps content to the physical pixel grid most sharply; use scaling rather than reducing resolution when text is too small."],
    ["What is color gamut?","The range of colors a display can reproduce; it is related to but distinct from brightness, contrast, and color depth."],
    ["Faint image visible under a flashlight suggests what?","The image signal may work while the backlight, inverter/driver, cable, or power path has failed." ]
  ],
  "3.2 · Cables & connectors": [
    ["UTP versus STP?","UTP relies on twisting; STP adds foil/braid for EMI control and requires correct grounding."],
    ["Plenum-rated versus direct-burial cable?","Plenum cable meets low-smoke/fire requirements for air spaces; direct-burial cable resists outdoor moisture/UV and follows burial code."],
    ["T568A versus T568B?","They assign the green and orange pairs differently. Same standard at both ends is straight-through; A-to-B is crossover."],
    ["Single-mode versus multimode fiber?","Single-mode uses a small core/laser for long distance; multimode uses a larger core for shorter building/data-center links."],
    ["ST, SC, and LC fiber clues?","ST is round bayonet, SC is square push-pull, and LC is a smaller latched connector."],
    ["RJ11, RJ45, and F-type uses?","RJ11 telephone/DSL, RJ45/8P8C Ethernet, and F-type coax/cable service."],
    ["USB 2.0 maximum signaling rate?","480 Mb/s."],
    ["Why can two USB-C cables behave differently?","The connector shape does not guarantee supported data speed, charging power, video alt mode, or Thunderbolt wiring."],
    ["HDMI, DisplayPort, DVI, and VGA signal clue?","HDMI/DP are digital audio/video, DVI variants are digital and/or analog, and VGA is analog video."],
    ["When is an active converter required?","When signal formats differ, such as analog VGA to digital HDMI; a passive shape adapter is insufficient."],
    ["SATA data and power pin counts?","7-pin data and 15-pin power."],
    ["Molex and DB9 uses?","Molex is legacy peripheral power; DB9 commonly carries legacy RS-232 serial." ]
  ],
  "3.3 · RAM": [
    ["DIMM versus SODIMM?","DIMMs are full-size desktop/server modules; SODIMMs are shorter laptop/small-system modules."],
    ["Are DDR3, DDR4, and DDR5 interchangeable?","No. Keying, pinout, voltage, signaling, and controller support differ."],
    ["DDR4 and DDR5 desktop DIMM pin counts?","Both have 288 pins, but different notch/pinout makes them incompatible."],
    ["DDR4 and DDR5 SODIMM pin counts?","260 and 262 respectively."],
    ["What does ECC RAM provide?","Detection and correction of supported memory errors, but only when CPU, motherboard, and firmware support ECC operation."],
    ["What is dual-channel memory?","Two memory channels populated according to the motherboard's required paired-slot arrangement, increasing available bandwidth."],
    ["Why should multichannel modules match?","Mismatched capacity, speed, timings, or organization can reduce speed, disable optimal channel mode, or cause instability."],
    ["What does DDR5-4800 mean?","A rated transfer rate of 4,800 MT/s; one 64-bit channel has theoretical 38,400 MB/s bandwidth."],
    ["First response to no POST after RAM installation?","Power off, verify compatibility and slot order, reseat, then test one known-good module/slot at a time."],
    ["Why might usable RAM be less than installed RAM?","Integrated graphics/hardware reservations, OS architecture/edition limits, firmware settings, or a failed/unrecognized module." ]
  ],
  "3.4 · Storage & RAID": [
    ["HDD versus SSD?","HDDs use magnetic spinning media and offer low cost per TB; SSDs use flash and offer lower latency, higher IOPS, silence, and shock resistance."],
    ["Common HDD form factors and spindle speeds?","3.5-inch desktop and 2.5-inch laptop; common speeds include 5,400 and 7,200 RPM."],
    ["Why is M.2 not synonymous with NVMe?","M.2 is a form factor. An M.2 device may use SATA/AHCI or PCIe/NVMe depending on drive and slot support."],
    ["SATA, SAS, PCIe, and NVMe relationship?","SATA/SAS/PCIe are connection fabrics/interfaces; NVMe is a low-overhead storage protocol over PCIe."],
    ["What does TRIM do?","Tells an SSD which logical blocks no longer hold live data so garbage collection need not preserve them."],
    ["RAID 0 properties?","Striping, minimum two drives, full combined capacity, improved parallel performance, and no fault tolerance."],
    ["RAID 1 properties?","Mirroring, minimum two drives, typically one drive of usable capacity in a two-drive set, and survival of one member failure."],
    ["RAID 5 and RAID 6?","RAID 5 uses distributed single parity, minimum three, tolerates one failure. RAID 6 uses dual parity, minimum four, tolerates two."],
    ["RAID 10 properties?","Striped mirrored pairs, minimum four; high performance/redundancy, with tolerance depending on which mirror members fail."],
    ["Why is RAID not backup?","Deletion, ransomware, corruption, controller mistakes, theft, and disaster can affect the entire array."],
    ["USB flash, SD/microSD, and optical media role?","Removable storage for transfer/offline use; verify capacity/speed class, physical compatibility, and safe ejection."],
    ["ROM, R, and RW/RE optical suffixes?","Read-only, recordable once, and rewritable." ]
  ],
  "3.5 · Motherboards, CPUs & add-on cards": [
    ["ATX, microATX, and Mini-ITX?","ATX is full-size with most expansion, microATX is smaller with fewer slots, and Mini-ITX is compact with tight expansion/cooling constraints."],
    ["Why are motherboard standoffs safety-critical?","Missing standoffs leave the board unsupported; an extra standoff under circuitry can short the board."],
    ["Main motherboard and CPU power connectors?","24-pin ATX main power and 4/8-pin EPS12V CPU power."],
    ["PCIe lane count versus physical slot length?","A long slot may be electrically wired for fewer lanes; the card/link negotiates supported generation and lane count."],
    ["What must match for CPU compatibility?","Exact socket/package, chipset, firmware support, power/TDP, memory controller, and cooler mounting—not merely Intel versus AMD."],
    ["x86, x64, and ARM?","x86 is 32-bit PC architecture, x64 is its 64-bit extension, and ARM is a RISC-derived architecture common in efficient mobile/embedded and newer computer systems."],
    ["Core versus thread?","A core is a physical execution engine; SMT can expose multiple logical threads per core, but does not double all workloads."],
    ["L1, L2, and L3 cache?","L1 is smallest/fastest and usually per core; L2 is larger; L3 is often the larger shared last-level cache."],
    ["Secure Boot versus firmware password?","Secure Boot validates trusted boot software; a firmware password restricts boot access or settings. They solve different problems."],
    ["TPM versus HSM?","TPM is a local platform key/measurement component; HSM is a dedicated enterprise cryptographic device/service."],
    ["Which UEFI settings are high yield?","Boot order, USB permissions, TPM, Secure Boot, boot/admin passwords, temperature/fan control, virtualization, and device enablement."],
    ["Common expansion cards?","Video/GPU, sound, capture, NIC, and storage/RAID/HBA cards; verify slot, lanes, power, cooling, connectors, and drivers."],
    ["Heat sink, paste/pad, fan, and liquid cooling roles?","Heat sink spreads heat; interface material fills microscopic gaps; fan moves air; liquid moves heat to a radiator."],
    ["What must happen after mounting a CPU cooler?","Connect the correct CPU-fan/pump header and verify firmware temperature before applying load." ]
  ],
  "3.6 · Power supplies": [
    ["North American versus many international mains input?","Approximately 110–120 VAC versus 220–240 VAC. Use a compatible auto-ranging PSU or correct selector setting."],
    ["PC PSU output rails?","3.3 V, 5 V, and 12 V DC rails supply different components; modern CPU/GPU loads rely heavily on 12 V."],
    ["What is the 20+4 connector?","A main motherboard connector that combines to 24 pins while retaining compatibility with some older 20-pin boards."],
    ["Which connectors power CPU, GPU, SATA drives, and legacy peripherals?","EPS12V 4/8-pin; PCIe 6/8-pin or 12VHPWR/12V-2x6 as supported; SATA 15-pin; Molex 4-pin."],
    ["Modular PSU advantage and risk?","Use only needed cables for airflow/management, but modular cables are not safely interchangeable across PSU models even if plugs fit."],
    ["What is a redundant PSU?","Two or more hot-swappable power modules designed so a supported system can continue if one module/source fails."],
    ["How should PSU wattage be selected?","Add realistic CPU, GPU, drives, fans, and peripherals; include transient/headroom and required connectors rather than choosing by wattage alone."],
    ["What does 80 PLUS describe?","Efficiency certification at specified loads/input conditions, not output quality or sufficient wattage by itself."],
    ["Why should a technician never open a PSU?","Capacitors can retain dangerous voltage even after unplugging; replace/test externally using approved procedure."],
    ["First checks after a PSU replacement produces no power?","Outlet/protection, rear switch/input setting, 24-pin and EPS connections, front-panel lead, modular PSU-side seating, and shorts/standoffs." ]
  ],
  "3.7 · Printer deployment & configuration": [
    ["What should printer placement account for?","Power/network access, ventilation, heat/moisture/dust, physical space, paper/consumable service clearance, noise, and user accessibility."],
    ["What must be removed during printer unboxing?","All shipping locks, tapes, spacers, cartridge/drum seals, and transport materials according to the setup guide."],
    ["PCL versus PostScript?","PCL is common printer-control language; PostScript emphasizes device-independent page description/graphics. Use the correct supported driver."],
    ["Why update printer firmware carefully?","It can fix security/compatibility bugs, but wrong/interrupted firmware can disable the device; verify model and preserve power."],
    ["USB, Ethernet, and wireless printer deployment difference?","USB is local/direct; Ethernet/Wi-Fi need valid network settings, reachability, and a stable queue/port address."],
    ["Printer share versus print server?","A workstation share depends on that host; a dedicated/server-based print service centralizes queues, drivers, permissions, and management."],
    ["Duplex, orientation, tray, and quality?","Two-sided printing; portrait/landscape; selected paper source/size/type; and DPI/color/quality settings."],
    ["What are secured print and badge release?","Hold a job until the authorized user enters a PIN/authenticates or presents a badge, reducing exposed documents."],
    ["Why keep printer audit logs?","Track users, jobs, access, failures, and security events for accountability and troubleshooting."],
    ["Network scan destinations in the objective?","Email, SMB file shares, and cloud services; each requires correct addressing, credentials, permissions, certificates, and time/DNS."],
    ["ADF versus flatbed scanner?","ADF feeds multiple loose pages automatically; flatbed handles books, photos, fragile originals, and single sheets."],
    ["Why prefer DHCP reservation or stable addressing for a network printer?","A changing address can leave clients/queues pointing to the old IP." ]
  ],
  "3.8 · Printer maintenance": [
    ["Core laser maintenance tasks?","Replace toner, install the correct maintenance kit, calibrate, and clean using manufacturer procedure."],
    ["What may a laser maintenance kit contain?","Commonly fuser and pickup/transfer rollers; exact contents vary. Toner/drum may be separate consumables."],
    ["Why let a laser printer cool before service?","The fuser operates at high temperature and can burn the technician."],
    ["Core inkjet maintenance tasks?","Replace ink, clean/align printheads, clean/replace rollers/feeders as supported, calibrate, and clear jams."],
    ["What causes missing inkjet lines/colors?","Clogged nozzles, empty/blocked cartridge, alignment, or printhead failure; use the printer's cleaning/test routine first."],
    ["Core thermal-printer maintenance?","Load correct thermal paper in the proper orientation, clean the heating element, inspect feed assembly, and remove debris."],
    ["How can you test whether thermal paper is loaded correctly?","Scratch a corner; the heat-sensitive side should darken."],
    ["Core impact-printer maintenance?","Replace ribbon, printhead/pins, and multipart/tractor-feed paper as required; inspect alignment and feed path."],
    ["Why remove a paper jam in the normal path without tearing it?","Pulling backward or leaving scraps can damage sensors/rollers and cause repeated jams."],
    ["What should follow any printer maintenance?","Reassemble, run internal/configuration and quality tests, verify options/consumables, clean the area, and document work." ]
  ],

  "4.1 · Virtualization": [
    ["Host, guest, and hypervisor?","The host supplies physical resources, the guest is the VM operating system, and the hypervisor creates/manages virtual hardware."],
    ["Type 1 versus Type 2 hypervisor?","Type 1 runs directly on hardware; Type 2 runs as an application on a host OS."],
    ["Why use a VM sandbox?","Isolate testing, malware analysis, risky changes, or untrusted applications from the primary environment, while remembering isolation is not perfect."],
    ["Application virtualization use?","Run an app in an isolated/packaged environment, often supporting legacy or cross-platform deployment without a full user-managed VM."],
    ["What resources must be planned for VMs?","CPU, RAM, storage capacity/IOPS, network mode/bandwidth, security, and host overhead."],
    ["What is overcommitment?","Assigning more virtual resources than physical capacity based on expected non-simultaneous use; excessive overcommit causes contention."],
    ["Bridged, NAT, and host-only VM networking?","Bridged joins the physical LAN; NAT uses a private virtual subnet with outbound translation; host-only limits communication to host/private guests."],
    ["What is VDI?","Virtual Desktop Infrastructure centrally hosts user desktops and delivers their interface remotely."],
    ["Container versus VM?","Containers share the host kernel and isolate processes; VMs run separate guest kernels on virtual hardware."],
    ["Why are snapshots not backups by themselves?","They may depend on the original virtual disk/datastore and do not provide independent off-system recovery." ]
  ],
  "4.2 · Cloud computing": [
    ["SaaS, PaaS, and IaaS?","SaaS provides a finished application; PaaS provides managed runtime/development platform; IaaS provides virtual compute, storage, and networking."],
    ["Public, private, hybrid, and community cloud?","Public is provider-shared; private serves one organization; hybrid combines environments; community is shared by organizations with common needs."],
    ["Resource pooling and multitenancy?","Providers pool infrastructure among customers; multitenancy isolates tenants sharing underlying systems."],
    ["Shared versus dedicated cloud resources?","Shared resources improve utilization/cost; dedicated resources provide reserved isolation/control at greater cost."],
    ["What is rapid elasticity?","Capacity can expand or contract quickly with demand, often automatically."],
    ["What is metered utilization?","Usage is measured for billing/management, such as compute time, storage, requests, or transferred data."],
    ["Ingress versus egress?","Ingress enters the cloud/provider; egress leaves it. Egress frequently incurs charges."],
    ["What does cloud availability mean?","Service remains accessible despite failures through redundancy/design, but exact guarantees depend on architecture and SLA."],
    ["What is cloud file synchronization?","Maintain updated copies across devices/cloud, resolving or exposing conflicts; synchronization is not automatically a versioned backup."],
    ["Who manages the OS in each service model?","Usually customer in IaaS; provider in PaaS and SaaS, while responsibility for data, identity, and configuration remains shared." ]
  ],

  "5.1 · Motherboard, RAM, CPU & power troubleshooting": [
    ["What should POST beeps/LEDs be compared against?","The exact motherboard/system vendor documentation; code meanings are not universal."],
    ["First path for a blank screen during POST?","Check power/input/cable, diagnostic codes, GPU/integrated output, RAM seating, and minimal hardware configuration."],
    ["No-power isolation order?","Outlet/protection device, cord, PSU switch/input, external disconnects, front-panel lead, internal power connectors, then PSU tester/known-good PSU."],
    ["What can cause sluggish performance?","CPU/RAM/storage contention, overheating/throttling, malware, background workload, power mode, failing storage, or insufficient resources."],
    ["Overheating response?","Verify fans/pump, dust/airflow, heat-sink mounting/interface material, firmware temperatures, workload, and overclocking."],
    ["Burning smell response?","Shut down and disconnect power immediately; inspect PSU, connectors, board, drives, cables, and swollen/leaking components before reuse."],
    ["Random shutdown likely categories?","Thermal protection, unstable/insufficient PSU, motherboard/CPU/RAM fault, or power-source interruption."],
    ["How isolate suspected RAM?","Verify compatibility, reseat, test one module and slot at a time, run memory diagnostics, and remove overclocking."],
    ["What does capacitor swelling imply?","Physical motherboard/PSU component failure; replace the affected assembly rather than continuing operation."],
    ["Inaccurate system date/time after power-off suggests what?","Weak CMOS/RTC battery, commonly a roughly 3 V CR2032; OS-only drift points more toward time synchronization." ]
  ],
  "5.2 · Drive & RAID troubleshooting": [
    ["Drive not detected versus OS not found?","Not detected means firmware/controller cannot see usable hardware; OS not found usually means a visible drive lacks valid boot information/order."],
    ["Clicking or grinding HDD response?","Stop normal use and prioritize backup/imaging or professional recovery; repeated stress may worsen physical failure."],
    ["Extended read/write times can indicate what?","Retries from bad media, failing drive/cable, heavy workload, low free space, heat, paging, malware, or controller/interface problems."],
    ["What does SMART provide?","Drive health attributes and warnings; trends are useful but SMART OK does not overrule obvious physical symptoms."],
    ["What is IOPS?","Input/output operations per second, especially relevant to random I/O; compare workload and device expectations rather than one number alone."],
    ["Missing drive in firmware isolation?","Check power/data connection, port, controller mode, M.2 slot sharing/key, firmware, and drive hardware."],
    ["Missing drive only in OS isolation?","Check controller driver, Disk Management, initialization/partition/filesystem, drive letter/mount, and mapped-network-drive state."],
    ["Degraded RAID response?","Record configuration, identify the exact failed member by slot/serial, preserve backup, replace compatibly, and monitor rebuild."],
    ["What can make an entire RAID array disappear?","Disabled/changed RAID firmware mode, controller failure/driver, multiple disconnected members, backplane/power, or corrupted configuration."],
    ["Why treat a RAID audible alarm urgently?","It may report degraded redundancy, failed member, cache/battery, temperature, or controller fault while data is at increased risk." ]
  ],
  "5.3 · Display & projector troubleshooting": [
    ["First display checks?","Power/wake, brightness, correct input source, cable/adapter, display mode/Fn key, then known-good display/port."],
    ["Fuzzy image on LCD?","Set native resolution/scaling, verify cable/signal quality, and check application/font smoothing before replacing hardware."],
    ["Flashing/intermittent screen causes?","Loose/damaged cable, unsupported refresh, driver, GPU heat/power, panel backlight/driver, or failing display hardware."],
    ["Incorrect display color causes?","Loose analog/digital cable pin, color profile/calibration, night mode/HDR mismatch, driver/GPU, or panel failure."],
    ["Dead pixel versus burn-in?","Dead/stuck pixels affect individual pixels; burn-in/image retention follows persistent static content across an area."],
    ["No display audio checks?","Selected playback device, HDMI/DP audio support, monitor volume/mute, cable/adapter capability, and driver."],
    ["Dim projector image causes?","Lamp age, eco mode, dirty filter/lens, ambient light, incorrect settings, or optical failure."],
    ["Intermittent projector shutdown often indicates what?","Overheating from blocked airflow/dirty filter, failing fan/lamp, power issue, or thermal protection."],
    ["Keystone versus resolution correction?","Keystone adjusts trapezoid geometry from projection angle; native resolution/focus addresses pixel sharpness."],
    ["How isolate display versus source?","Test the display with another source and the source with another display/cable; follow the failure." ]
  ],
  "5.4 · Mobile-device troubleshooting": [
    ["Poor battery runtime causes besides age?","High brightness, background apps, weak-signal searching, radios/GPS, gaming/streaming, updates, heat, or malware."],
    ["Improper charging isolation?","Known-good compatible cable/adapter/outlet, inspect/clean port safely, check wattage/protocol and temperature, then battery/board."],
    ["What is an LCI?","Liquid contact indicator near areas such as charging/SIM openings; it changes color after exposure and helps confirm liquid damage."],
    ["Liquid-damage first response?","Power off, disconnect charging, remove case/cards/removable battery if safe, blot and follow approved drying/service; do not keep testing or apply heat."],
    ["Cursor drift/ghost touch suggests what?","Moisture/debris, case/protector pressure, calibration, digitizer/cable failure—not necessarily malware."],
    ["Unable to install an app checks?","Free storage, network, app-store authentication, OS/device compatibility, policy/MDM restrictions, and trusted source."],
    ["Mobile malware clues?","Unexpected apps/pop-ups, redirects, high data/battery/CPU use, overheating, or suspicious permissions."],
    ["Stylus troubleshooting?","Compatibility, charge/battery, tip damage, Bluetooth pairing, calibration, digitizer, and restart/reset."],
    ["Degraded mobile performance path?","Restart, inspect storage and high-use apps, update supported OS/apps, check heat/battery/malware, back up before reset."],
    ["Why use a manufacturer-specific forced restart?","Button combinations vary by model; it can recover a black/unresponsive device without guessing or disassembly." ]
  ],
  "5.5 · Network troubleshooting": [
    ["Outward network test order?","Link/association → loopback → local IP → gateway → external IP → DNS name → application/port."],
    ["What does APIPA tell you?","The host self-assigned 169.254.x.x because normal IPv4 configuration, usually DHCP, failed."],
    ["External IP works but hostname fails?","Investigate DNS server/configuration/cache/records rather than the basic routed path."],
    ["What is port flapping?","A physical/logical link repeatedly goes up and down; test cable, connector, NIC, switch port, transceiver, power, and negotiation."],
    ["Latency versus jitter?","Latency is delay; jitter is variation in delay. Both harm real-time traffic, while loss creates gaps/retransmissions."],
    ["Poor VoIP quality checks?","Latency, jitter, loss, congestion/bandwidth, Wi-Fi signal/interference, QoS, endpoint, and provider path."],
    ["What is multipath interference?","Reflected wireless signals arrive along different paths/times and interfere; reposition AP/antenna or change environment/channel."],
    ["What does a high SNR mean?","Useful wireless signal is much stronger than background noise; higher signal-to-noise ratio is better."],
    ["Authentication versus authorization failure?","Authentication cannot prove identity; authorization denies a known identity's requested resource/action."],
    ["How investigate intermittent Internet service?","Continuous timestamped ping/traceroute/speed tests, interface/AP logs and packet capture, then correlate/escalate against provider SLA." ]
  ],
  "5.6 · Printer troubleshooting": [
    ["Internal versus OS printer test page?","Internal bypasses computer/driver; OS test bypasses the application but tests OS, driver, connection, and printer."],
    ["Vertical line on inkjet versus laser?","Inkjet often dirty/clogged head; laser often scratched drum or contaminated imaging/transfer path."],
    ["Faded print causes?","Low toner/ink, economy/density setting, dirty optics/head, or transfer/imaging issue."],
    ["Speckling or double/echo image on laser output?","Drum/cleaning/fuser/imaging component may retain or repeat toner from a prior rotation."],
    ["Garbled print causes?","Wrong/corrupt driver, PCL/PostScript mismatch, bad data/cable, printer memory/controller, or application output."],
    ["Paper not feeding versus multipage misfeed?","No feed points to pickup roller/tray/media; multiple sheets point to separation pad/roller or media humidity/static."],
    ["Frozen queue response?","Identify/remove corrupt job, restart Print Spooler as needed, inspect PrintService logs, then update/recreate driver/queue if recurring."],
    ["Grinding noise response?","Stop printing; inspect for jam, foreign object, damaged gear, or improperly seated cartridge."],
    ["Finishing issues include what?","Staple jams, hole-punch alignment/waste, collation, sorting, and output-finisher configuration."],
    ["Tray not recognized causes?","Tray physically misseated, size/type mismatch, driver option not enabled, sensor/firmware fault, or incorrect application selection." ]
  ]
} };
